In [1]:
# Task 1: Vehicle_ID Trimming & Canonical Case
import pandas as pd

df = pd.read_csv("car_rental_dirty_dataset_new1.csv")

1. Vehicle_ID trimming and canonical case.

In [2]:
unique_vid = df['Vehicle_ID'].nunique()

# Inspect raw Vehicle_ID values
print(f"Shape: {df.shape}")
print(f"Unique Vehicle_IDs (raw): {unique_vid}")
print(sorted(df['Vehicle_ID'].dropna().unique()))
print(f"\n{df['Vehicle_ID'].value_counts().sort_index()}")

Shape: (5000, 21)
Unique Vehicle_IDs (raw): 601
[' CAR-008 ', ' CAR-009 ', ' CAR-019 ', ' CAR-041 ', ' CAR-046 ', ' CAR-056 ', ' CAR-058 ', ' CAR-059 ', ' CAR-062 ', ' CAR-070 ', ' CAR-078 ', ' CAR-079 ', ' CAR-084 ', ' CAR-091 ', ' CAR-099 ', ' CAR-103 ', ' CAR-105 ', ' CAR-108 ', ' CAR-115 ', ' CAR-120 ', ' CAR-124 ', ' CAR-130 ', ' CAR-145 ', ' CAR-182 ', ' CAR-189 ', ' CAR-201 ', ' CAR-216 ', ' CAR-222 ', ' CAR-240 ', ' CAR-255 ', ' CAR-258 ', ' CAR-259 ', ' CAR-264 ', ' CAR-285 ', ' CAR-298 ', ' CAR-348 ', ' CAR-349 ', ' CAR-352 ', ' CAR-358 ', ' CAR-367 ', ' CAR-390 ', ' CAR-401 ', ' CAR-406 ', ' CAR-411 ', ' CAR-425 ', ' CAR-432 ', ' CAR-439 ', ' CAR-443 ', ' CAR-445 ', ' CAR-448 ', ' CAR-460 ', ' CAR-461 ', ' CAR-491 ', ' CAR-511 ', ' CAR-515 ', ' CAR-519 ', ' CAR-535 ', ' CAR-540 ', ' CAR-541 ', ' CAR-545 ', ' CAR-547 ', ' CAR-557 ', ' CAR-562 ', ' CAR-566 ', ' CAR-570 ', ' CAR-573 ', ' CAR-574 ', ' CAR-580 ', ' CAR-585 ', ' CAR-600 ', 'CAR 025', 'CAR 030', 'CAR 032', 'CAR 038', 'CAR 042', 'CAR 050', 'CAR 055', 'CAR 065', 'CAR 077', 'CAR 092', 'CAR 104', 'CAR 106', 'CAR 119', 'CAR 131', 'CAR 136', 'CAR 146', 'CAR 149', 'CAR 152', 'CAR 161', 'CAR 166', 'CAR 168', 'CAR 177', 'CAR 183', 'CAR 186', 'CAR 187', 'CAR 198', 'CAR 199', 'CAR 202', 'CAR 203', 'CAR 215', 'CAR 226', 'CAR 234', 'CAR 237', 'CAR 244', 'CAR 251', 'CAR 267', 'CAR 268', 'CAR 279', 'CAR 281', 'CAR 297', 'CAR 301', 'CAR 306', 'CAR 320', 'CAR 321', 'CAR 330', 'CAR 331', 'CAR 333', 'CAR 337', 'CAR 346', 'CAR 347', 'CAR 357', 'CAR 359', 'CAR 370', 'CAR 375', 'CAR 398', 'CAR 403', 'CAR 426', 'CAR 435', 'CAR 444', 'CAR 466', 'CAR 469', 'CAR 478', 'CAR 479', 'CAR 481', 'CAR 498', 'CAR 499', 'CAR 502', 'CAR 505', 'CAR 506', 'CAR 507', 'CAR 514', 'CAR 520', 'CAR 528', 'CAR 538', 'CAR 543', 'CAR 549', 'CAR 550', 'CAR 558', 'CAR 559', 'CAR 560', 'CAR 568', 'CAR 587', 'CAR 588', 'CAR 590', 'CAR 595', 'CAR 597', 'CAR-003', 'CAR-004', 'CAR-005', 'CAR-007', 'CAR-010 ', 'CAR-012', 'CAR-015 ', 'CAR-018', 'CAR-020 ', 'CAR-021', 'CAR-022', 'CAR-024 ', 'CAR-026 ', 'CAR-027 ', 'CAR-028 ', 'CAR-033', 'CAR-034 ', 'CAR-035 ', 'CAR-037 ', 'CAR-049 ', 'CAR-052 ', 'CAR-053 ', 'CAR-064', 'CAR-071', 'CAR-076', 'CAR-081 ', 'CAR-086 ', 'CAR-087 ', 'CAR-109', 'CAR-111', 'CAR-113 ', 'CAR-118', 'CAR-123 ', 'CAR-129', 'CAR-133 ', 'CAR-138 ', 'CAR-140 ', 'CAR-143 ', 'CAR-144', 'CAR-150 ', 'CAR-153 ', 'CAR-156 ', 'CAR-159', 'CAR-165', 'CAR-170 ', 'CAR-174 ', 'CAR-184', 'CAR-185 ', 'CAR-190', 'CAR-191 ', 'CAR-197 ', 'CAR-214 ', 'CAR-219 ', 'CAR-220 ', 'CAR-221', 'CAR-232', 'CAR-238 ', 'CAR-239 ', 'CAR-241', 'CAR-243 ', 'CAR-246', 'CAR-250 ', 'CAR-254 ', 'CAR-265 ', 'CAR-271 ', 'CAR-274', 'CAR-289 ', 'CAR-291', 'CAR-292', 'CAR-294', 'CAR-295', 'CAR-296', 'CAR-300', 'CAR-304', 'CAR-305 ', 'CAR-307 ', 'CAR-308', 'CAR-313 ', 'CAR-319', 'CAR-326 ', 'CAR-327', 'CAR-334 ', 'CAR-341', 'CAR-343 ', 'CAR-350', 'CAR-351', 'CAR-356 ', 'CAR-360', 'CAR-362', 'CAR-363', 'CAR-368 ', 'CAR-369 ', 'CAR-376', 'CAR-377', 'CAR-379 ', 'CAR-383', 'CAR-384 ', 'CAR-392', 'CAR-395', 'CAR-396', 'CAR-402 ', 'CAR-409', 'CAR-412 ', 'CAR-430', 'CAR-434', 'CAR-436 ', 'CAR-441', 'CAR-450', 'CAR-453', 'CAR-455', 'CAR-458 ', 'CAR-459 ', 'CAR-462', 'CAR-465 ', 'CAR-467', 'CAR-473', 'CAR-482', 'CAR-483 ', 'CAR-489', 'CAR-492 ', 'CAR-493', 'CAR-504', 'CAR-512', 'CAR-513', 'CAR-518', 'CAR-522', 'CAR-523', 'CAR-524 ', 'CAR-530 ', 'CAR-537', 'CAR-539', 'CAR-544', 'CAR-551', 'CAR-555', 'CAR-561 ', 'CAR-564', 'CAR-567', 'CAR-572', 'CAR-575 ', 'CAR-576 ', 'CAR-581 ', 'CAR-594 ', 'CAR-596 ', 'CAR-599', 'CAR001', 'CAR017', 'CAR029', 'CAR031', 'CAR036', 'CAR039', 'CAR044', 'CAR048', 'CAR066', 'CAR067', 'CAR080', 'CAR082', 'CAR089', 'CAR090', 'CAR094', 'CAR095', 'CAR098', 'CAR102', 'CAR134', 'CAR151', 'CAR171', 'CAR175', 'CAR176', 'CAR178', 'CAR179', 'CAR180', 'CAR192', 'CAR193', 'CAR195', 'CAR200', 'CAR209', 'CAR212', 'CAR227', 'CAR231', 'CAR242', 'CAR249', 'CAR263', 'CAR276', 'CAR280', 'CAR282', 'CAR287', 'CAR299', 'CAR317', 'CAR324', 'CAR332', 'CAR336', 'CAR342', 'CAR389', 'CAR397', 'CAR399', 'CAR407', 'CAR408', 'CAR415', 'CAR418', 'CAR419', 'CAR442', 'CAR451', 'CAR454', 'CAR468', 'CAR486', 'CAR487', 'CAR488', 'CAR496', 'CAR501', 'CAR517', 'CAR526', 'CAR534', 'CAR548', 'CAR554', 'CAR556', 'CAR589', 'CAR_002', 'CAR_013', 'CAR_014', 'CAR_045', 'CAR_101', 'CAR_110', 'CAR_114', 'CAR_117', 'CAR_122', 'CAR_125', 'CAR_127', 'CAR_128', 'CAR_132', 'CAR_142', 'CAR_155', 'CAR_160', 'CAR_172', 'CAR_173', 'CAR_181', 'CAR_196', 'CAR_205', 'CAR_206', 'CAR_217', 'CAR_225', 'CAR_229', 'CAR_233', 'CAR_235', 'CAR_236', 'CAR_247', 'CAR_269', 'CAR_283', 'CAR_302', 'CAR_309', 'CAR_312', 'CAR_316', 'CAR_329', 'CAR_339', 'CAR_344', 'CAR_345', 'CAR_353', 'CAR_355', 'CAR_361', 'CAR_364', 'CAR_371', 'CAR_374', 'CAR_378', 'CAR_382', 'CAR_388', 'CAR_427', 'CAR_438', 'CAR_440', 'CAR_446', 'CAR_463', 'CAR_471', 'CAR_477', 'CAR_480', 'CAR_500', 'CAR_516', 'CAR_525', 'CAR_529', 'CAR_546', 'CAR_563', 'CAR_565', 'CAR_571', 'CAR_586', 'CAR_592', 'UNKNOWN', 'car-006', 'car-011', 'car-016', 'car-040', 'car-047', 'car-061', 'car-063', 'car-068', 'car-069', 'car-072', 'car-075', 'car-083', 'car-085', 'car-088', 'car-093', 'car-096', 'car-107', 'car-116', 'car-137', 'car-141', 'car-157', 'car-162', 'car-164', 'car-167', 'car-169', 'car-188', 'car-208', 'car-211', 'car-213', 'car-218', 'car-223', 'car-228', 'car-245', 'car-248', 'car-253', 'car-256', 'car-260', 'car-272', 'car-277', 'car-278', 'car-284', 'car-303', 'car-311', 'car-315', 'car-322', 'car-323', 'car-338', 'car-340', 'car-366', 'car-372', 'car-373', 'car-380', 'car-391', 'car-393', 'car-394', 'car-404', 'car-405', 'car-410', 'car-414', 'car-416', 'car-417', 'car-422', 'car-424', 'car-428', 'car-429', 'car-433', 'car-452', 'car-456', 'car-470', 'car-472', 'car-474', 'car-484', 'car-485', 'car-490', 'car-494', 'car-495', 'car-497', 'car-508', 'car-509', 'car-527', 'car-533', 'car-552', 'car-578', 'car-579', 'car-582', 'car-583', 'car-591', 'car-593', 'car023', 'car043', 'car051', 'car054', 'car057', 'car060', 'car073', 'car074', 'car097', 'car100', 'car112', 'car121', 'car126', 'car135', 'car139', 'car147', 'car148', 'car154', 'car158', 'car163', 'car194', 'car204', 'car207', 'car210', 'car224', 'car230', 'car252', 'car257', 'car261', 'car262', 'car266', 'car270', 'car273', 'car275', 'car286', 'car288', 'car290', 'car293', 'car310', 'car314', 'car318', 'car325', 'car328', 'car335', 'car354', 'car365', 'car381', 'car385', 'car386', 'car387', 'car400', 'car413', 'car420', 'car421', 'car423', 'car431', 'car437', 'car447', 'car449', 'car457', 'car464', 'car475', 'car476', 'car503', 'car510', 'car521', 'car531', 'car532', 'car536', 'car542', 'car553', 'car569', 'car577', 'car584', 'car598']

Vehicle_ID
 CAR-008     1
 CAR-009     5
 CAR-019     5
 CAR-041     6
 CAR-046     8
            ..
car553       8
car569       5
car577       7
car584       6
car598       7
Name: count, Length: 601, dtype: int64

In [3]:
# Clean Vehicle_ID: trim whitespace, normalize separators, canonical uppercase

# Strip leading/trailing whitespace
df['Vehicle_ID'] = df['Vehicle_ID'].str.strip()

# Normalize separators: double hyphens -> single, underscores -> hyphens
df['Vehicle_ID'] = df['Vehicle_ID'].str.replace('--', '-', regex=False)
df['Vehicle_ID'] = df['Vehicle_ID'].str.replace('_', '-', regex=False)

# Insert hyphen between letters and digits where missing (e.g., CAR08 -> CAR-08)
df['Vehicle_ID'] = df['Vehicle_ID'].str.replace(r'([A-Za-z])\s+(\d)', r'\1-\2', regex=True)
df['Vehicle_ID'] = df['Vehicle_ID'].str.replace(r'([A-Za-z])(\d)', r'\1-\2', regex=True)

# Convert to uppercase canonical form
df['Vehicle_ID'] = df['Vehicle_ID'].str.upper()

# Fix CAR-004 -> CAR-04 to match 2-digit format
df['Vehicle_ID'] = df['Vehicle_ID'].replace('CAR-004', 'CAR-04')

# Convert 'UNKNOWN' to NaN, flag invalid IDs
df['Vehicle_ID_Invalid'] = df['Vehicle_ID'].isna() | (df['Vehicle_ID'] == 'UNKNOWN')
df.loc[df['Vehicle_ID'] == 'UNKNOWN', 'Vehicle_ID'] = pd.NA

print("Cleaned Vehicle_IDs:")
print(sorted(df['Vehicle_ID'].dropna().unique()))
print(f"\n{df['Vehicle_ID'].value_counts().sort_index()}")

Cleaned Vehicle_IDs:
['CAR-001', 'CAR-002', 'CAR-003', 'CAR-005', 'CAR-006', 'CAR-007', 'CAR-008', 'CAR-009', 'CAR-010', 'CAR-011', 'CAR-012', 'CAR-013', 'CAR-014', 'CAR-015', 'CAR-016', 'CAR-017', 'CAR-018', 'CAR-019', 'CAR-020', 'CAR-021', 'CAR-022', 'CAR-023', 'CAR-024', 'CAR-025', 'CAR-026', 'CAR-027', 'CAR-028', 'CAR-029', 'CAR-030', 'CAR-031', 'CAR-032', 'CAR-033', 'CAR-034', 'CAR-035', 'CAR-036', 'CAR-037', 'CAR-038', 'CAR-039', 'CAR-04', 'CAR-040', 'CAR-041', 'CAR-042', 'CAR-043', 'CAR-044', 'CAR-045', 'CAR-046', 'CAR-047', 'CAR-048', 'CAR-049', 'CAR-050', 'CAR-051', 'CAR-052', 'CAR-053', 'CAR-054', 'CAR-055', 'CAR-056', 'CAR-057', 'CAR-058', 'CAR-059', 'CAR-060', 'CAR-061', 'CAR-062', 'CAR-063', 'CAR-064', 'CAR-065', 'CAR-066', 'CAR-067', 'CAR-068', 'CAR-069', 'CAR-070', 'CAR-071', 'CAR-072', 'CAR-073', 'CAR-074', 'CAR-075', 'CAR-076', 'CAR-077', 'CAR-078', 'CAR-079', 'CAR-080', 'CAR-081', 'CAR-082', 'CAR-083', 'CAR-084', 'CAR-085', 'CAR-086', 'CAR-087', 'CAR-088', 'CAR-089', 'CAR-090', 'CAR-091', 'CAR-092', 'CAR-093', 'CAR-094', 'CAR-095', 'CAR-096', 'CAR-097', 'CAR-098', 'CAR-099', 'CAR-100', 'CAR-101', 'CAR-102', 'CAR-103', 'CAR-104', 'CAR-105', 'CAR-106', 'CAR-107', 'CAR-108', 'CAR-109', 'CAR-110', 'CAR-111', 'CAR-112', 'CAR-113', 'CAR-114', 'CAR-115', 'CAR-116', 'CAR-117', 'CAR-118', 'CAR-119', 'CAR-120', 'CAR-121', 'CAR-122', 'CAR-123', 'CAR-124', 'CAR-125', 'CAR-126', 'CAR-127', 'CAR-128', 'CAR-129', 'CAR-130', 'CAR-131', 'CAR-132', 'CAR-133', 'CAR-134', 'CAR-135', 'CAR-136', 'CAR-137', 'CAR-138', 'CAR-139', 'CAR-140', 'CAR-141', 'CAR-142', 'CAR-143', 'CAR-144', 'CAR-145', 'CAR-146', 'CAR-147', 'CAR-148', 'CAR-149', 'CAR-150', 'CAR-151', 'CAR-152', 'CAR-153', 'CAR-154', 'CAR-155', 'CAR-156', 'CAR-157', 'CAR-158', 'CAR-159', 'CAR-160', 'CAR-161', 'CAR-162', 'CAR-163', 'CAR-164', 'CAR-165', 'CAR-166', 'CAR-167', 'CAR-168', 'CAR-169', 'CAR-170', 'CAR-171', 'CAR-172', 'CAR-173', 'CAR-174', 'CAR-175', 'CAR-176', 'CAR-177', 'CAR-178', 'CAR-179', 'CAR-180', 'CAR-181', 'CAR-182', 'CAR-183', 'CAR-184', 'CAR-185', 'CAR-186', 'CAR-187', 'CAR-188', 'CAR-189', 'CAR-190', 'CAR-191', 'CAR-192', 'CAR-193', 'CAR-194', 'CAR-195', 'CAR-196', 'CAR-197', 'CAR-198', 'CAR-199', 'CAR-200', 'CAR-201', 'CAR-202', 'CAR-203', 'CAR-204', 'CAR-205', 'CAR-206', 'CAR-207', 'CAR-208', 'CAR-209', 'CAR-210', 'CAR-211', 'CAR-212', 'CAR-213', 'CAR-214', 'CAR-215', 'CAR-216', 'CAR-217', 'CAR-218', 'CAR-219', 'CAR-220', 'CAR-221', 'CAR-222', 'CAR-223', 'CAR-224', 'CAR-225', 'CAR-226', 'CAR-227', 'CAR-228', 'CAR-229', 'CAR-230', 'CAR-231', 'CAR-232', 'CAR-233', 'CAR-234', 'CAR-235', 'CAR-236', 'CAR-237', 'CAR-238', 'CAR-239', 'CAR-240', 'CAR-241', 'CAR-242', 'CAR-243', 'CAR-244', 'CAR-245', 'CAR-246', 'CAR-247', 'CAR-248', 'CAR-249', 'CAR-250', 'CAR-251', 'CAR-252', 'CAR-253', 'CAR-254', 'CAR-255', 'CAR-256', 'CAR-257', 'CAR-258', 'CAR-259', 'CAR-260', 'CAR-261', 'CAR-262', 'CAR-263', 'CAR-264', 'CAR-265', 'CAR-266', 'CAR-267', 'CAR-268', 'CAR-269', 'CAR-270', 'CAR-271', 'CAR-272', 'CAR-273', 'CAR-274', 'CAR-275', 'CAR-276', 'CAR-277', 'CAR-278', 'CAR-279', 'CAR-280', 'CAR-281', 'CAR-282', 'CAR-283', 'CAR-284', 'CAR-285', 'CAR-286', 'CAR-287', 'CAR-288', 'CAR-289', 'CAR-290', 'CAR-291', 'CAR-292', 'CAR-293', 'CAR-294', 'CAR-295', 'CAR-296', 'CAR-297', 'CAR-298', 'CAR-299', 'CAR-300', 'CAR-301', 'CAR-302', 'CAR-303', 'CAR-304', 'CAR-305', 'CAR-306', 'CAR-307', 'CAR-308', 'CAR-309', 'CAR-310', 'CAR-311', 'CAR-312', 'CAR-313', 'CAR-314', 'CAR-315', 'CAR-316', 'CAR-317', 'CAR-318', 'CAR-319', 'CAR-320', 'CAR-321', 'CAR-322', 'CAR-323', 'CAR-324', 'CAR-325', 'CAR-326', 'CAR-327', 'CAR-328', 'CAR-329', 'CAR-330', 'CAR-331', 'CAR-332', 'CAR-333', 'CAR-334', 'CAR-335', 'CAR-336', 'CAR-337', 'CAR-338', 'CAR-339', 'CAR-340', 'CAR-341', 'CAR-342', 'CAR-343', 'CAR-344', 'CAR-345', 'CAR-346', 'CAR-347', 'CAR-348', 'CAR-349', 'CAR-350', 'CAR-351', 'CAR-352', 'CAR-353', 'CAR-354', 'CAR-355', 'CAR-356', 'CAR-357', 'CAR-358', 'CAR-359', 'CAR-360', 'CAR-361', 'CAR-362', 'CAR-363', 'CAR-364', 'CAR-365', 'CAR-366', 'CAR-367', 'CAR-368', 'CAR-369', 'CAR-370', 'CAR-371', 'CAR-372', 'CAR-373', 'CAR-374', 'CAR-375', 'CAR-376', 'CAR-377', 'CAR-378', 'CAR-379', 'CAR-380', 'CAR-381', 'CAR-382', 'CAR-383', 'CAR-384', 'CAR-385', 'CAR-386', 'CAR-387', 'CAR-388', 'CAR-389', 'CAR-390', 'CAR-391', 'CAR-392', 'CAR-393', 'CAR-394', 'CAR-395', 'CAR-396', 'CAR-397', 'CAR-398', 'CAR-399', 'CAR-400', 'CAR-401', 'CAR-402', 'CAR-403', 'CAR-404', 'CAR-405', 'CAR-406', 'CAR-407', 'CAR-408', 'CAR-409', 'CAR-410', 'CAR-411', 'CAR-412', 'CAR-413', 'CAR-414', 'CAR-415', 'CAR-416', 'CAR-417', 'CAR-418', 'CAR-419', 'CAR-420', 'CAR-421', 'CAR-422', 'CAR-423', 'CAR-424', 'CAR-425', 'CAR-426', 'CAR-427', 'CAR-428', 'CAR-429', 'CAR-430', 'CAR-431', 'CAR-432', 'CAR-433', 'CAR-434', 'CAR-435', 'CAR-436', 'CAR-437', 'CAR-438', 'CAR-439', 'CAR-440', 'CAR-441', 'CAR-442', 'CAR-443', 'CAR-444', 'CAR-445', 'CAR-446', 'CAR-447', 'CAR-448', 'CAR-449', 'CAR-450', 'CAR-451', 'CAR-452', 'CAR-453', 'CAR-454', 'CAR-455', 'CAR-456', 'CAR-457', 'CAR-458', 'CAR-459', 'CAR-460', 'CAR-461', 'CAR-462', 'CAR-463', 'CAR-464', 'CAR-465', 'CAR-466', 'CAR-467', 'CAR-468', 'CAR-469', 'CAR-470', 'CAR-471', 'CAR-472', 'CAR-473', 'CAR-474', 'CAR-475', 'CAR-476', 'CAR-477', 'CAR-478', 'CAR-479', 'CAR-480', 'CAR-481', 'CAR-482', 'CAR-483', 'CAR-484', 'CAR-485', 'CAR-486', 'CAR-487', 'CAR-488', 'CAR-489', 'CAR-490', 'CAR-491', 'CAR-492', 'CAR-493', 'CAR-494', 'CAR-495', 'CAR-496', 'CAR-497', 'CAR-498', 'CAR-499', 'CAR-500', 'CAR-501', 'CAR-502', 'CAR-503', 'CAR-504', 'CAR-505', 'CAR-506', 'CAR-507', 'CAR-508', 'CAR-509', 'CAR-510', 'CAR-511', 'CAR-512', 'CAR-513', 'CAR-514', 'CAR-515', 'CAR-516', 'CAR-517', 'CAR-518', 'CAR-519', 'CAR-520', 'CAR-521', 'CAR-522', 'CAR-523', 'CAR-524', 'CAR-525', 'CAR-526', 'CAR-527', 'CAR-528', 'CAR-529', 'CAR-530', 'CAR-531', 'CAR-532', 'CAR-533', 'CAR-534', 'CAR-535', 'CAR-536', 'CAR-537', 'CAR-538', 'CAR-539', 'CAR-540', 'CAR-541', 'CAR-542', 'CAR-543', 'CAR-544', 'CAR-545', 'CAR-546', 'CAR-547', 'CAR-548', 'CAR-549', 'CAR-550', 'CAR-551', 'CAR-552', 'CAR-553', 'CAR-554', 'CAR-555', 'CAR-556', 'CAR-557', 'CAR-558', 'CAR-559', 'CAR-560', 'CAR-561', 'CAR-562', 'CAR-563', 'CAR-564', 'CAR-565', 'CAR-566', 'CAR-567', 'CAR-568', 'CAR-569', 'CAR-570', 'CAR-571', 'CAR-572', 'CAR-573', 'CAR-574', 'CAR-575', 'CAR-576', 'CAR-577', 'CAR-578', 'CAR-579', 'CAR-580', 'CAR-581', 'CAR-582', 'CAR-583', 'CAR-584', 'CAR-585', 'CAR-586', 'CAR-587', 'CAR-588', 'CAR-589', 'CAR-590', 'CAR-591', 'CAR-592', 'CAR-593', 'CAR-594', 'CAR-595', 'CAR-596', 'CAR-597', 'CAR-598', 'CAR-599', 'CAR-600']

Vehicle_ID
CAR-001     7
CAR-002     8
CAR-003     7
CAR-005     8
CAR-006    13
           ..
CAR-596     6
CAR-597     9
CAR-598     7
CAR-599    13
CAR-600     4
Name: count, Length: 600, dtype: int64

In [4]:
# Validate: all non-null IDs should match CAR-XX or CAR-XXX
valid_ids = df['Vehicle_ID'].dropna()
pattern_match = valid_ids.str.match(r'^CAR-\d{2,3}$')

print(f"Valid IDs: {len(valid_ids)} | Matching pattern: {pattern_match.sum()} | Non-matching: {(~pattern_match).sum()}")
if (~pattern_match).any():
    print(f"Non-matching: {valid_ids[~pattern_match].unique()}")

print(f"\nUnique Vehicle_IDs — Before: {unique_vid}, After: {df['Vehicle_ID'].nunique()}")
print(f"Invalid (NaN) Vehicle_IDs: {df['Vehicle_ID'].isna().sum()}")

Valid IDs: 4988 | Matching pattern: 4988 | Non-matching: 0

Unique Vehicle_IDs — Before: 601, After: 600
Invalid (NaN) Vehicle_IDs: 12

2. Timestamp normalization; invalid minutes fix; duration must be positive.

In [5]:
import re
def fix_invalid_minutes(ts):
    if pd.isna(ts):
        return ts  
    match = re.search(r'(\d{1,2}):(\d{2})', str(ts))
    
    if match:
        hour = int(match.group(1))
        minute = int(match.group(2))
        
        if minute > 59:
            hour += minute // 60
            minute = minute % 60
        
        if hour > 23:
            hour = hour % 24
            
        ts = re.sub(r'\d{1,2}:\d{2}', f"{hour}:{minute:02d}", str(ts))
            
    return ts

In [6]:
df["Pickup_TS"] = df["Pickup_TS"].apply(fix_invalid_minutes)
df["Return_TS"] = df["Return_TS"].apply(fix_invalid_minutes)
df["Booking_TS"] = df["Booking_TS"].apply(fix_invalid_minutes)
df.head(20)

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_Status,Booking_TS,Pickup_TS,Return_TS,Odo_Start,Odo_End,...,Promo_Code,City,GPS_Lat,GPS_Lon,Speed,Payment,Driver_License,Damage_Flag,Notes,Vehicle_ID_Invalid
0,RES-00001,CUST-1407,CAR-151,Luxury,Completed,06/19/2026 0:59,2026-06-27T0:59,2026-06-27T15:59,40729,40787,...,NaN,mumbai,12.948007,77.635873,NaN,netbanking,DL-1170728882,NaN,Navigation system malfunction reported,False
1,RES-00002,CUST-1555,CAR-538,SUV,Cancelled,2026-05-22T11:21,2026-05-27T11:21,2026-05-30T3:21,54220,"54,561",...,WELCOME5,delhi,12.889665,77.635561,134 km/h,card,DL-8720768076,Minor,AC performance slightly low,False
2,RES-00003,CUST-0100,CAR-118,Sedan,No_Show,2026/06/19 5:29,2026/06/22 5:29,25-06-2026 2:29,33021 km,33149km,...,WELCOME5,CHN,12.872257,77.623025,NaN,wallet,DL-2540682838,Major,Customer requested early pickup,False
3,RES-00004,CUST-1480,CAR-085,NaN,Completed,2026-06-04T22:10,2026-06-07T22:10,2026/6/10 19:01,76471,"76,415",...,NaN,MUM,12.856798,77.618630,fast,UPI,DL-3314017702,NaN,Vehicle returned late due to traffic,False
4,RES-00005,CUST-0696,CAR-292,unknown,Cancelled,05/16/2026 9:24,05/23/2026 9:24,23-05-2026 11:24,45940,"46,332",...,DISC20,CHN,12.852438,77.640421,NaN,upi,DL-4018623004,NaN,Vehicle returned late due to traffic,False
5,RES-00006,CUST-0361,CAR-211,Sedan,Completed,2026-03-09T3:03,2026-03-14 3:03,16-03-2026 1:03,"12,565",12894km,...,NaN,Mumbai,12.905509,77.618185,NaN,CARD,DL-5961002183,NaN,AC performance slightly low,False
6,RES-00007,CUST-1834,CAR-164,unknown,Cancelled,2025-12-28 0:00,2026/01/01 0:00,2026/1/2 21:17,19508 km,"19,429",...,NEW10,Bengaluru,12.927118,77.637018,NaN,upi,DL-2941631094,NaN,Car returned in good condition,False
7,RES-00008,CUST-1613,CAR-149,SUV,Cancelled,2026-01-25T0:00,2026/2/1 1:04,02/02/2026 11:00,17715 km,17862km,...,SAVE50,Mumbai,12.911117,77.557031,140,upi,DL-9482900041,Major,Vehicle returned late due to traffic,False
8,RES-00009,CUST-0331,CAR-018,Luxury,No_Show,2026-05-01T5:01,2026-05-09 5:01,05/10/2026 3:01,66473 km,66546km,...,WELCOME5,delhi,12.946923,77.571583,69 km/h,UPI,DL-3510206236,NaN,Customer reported minor scratch on door,False
9,RES-00010,CUST-0880,CAR-223,Sedan,Completed,2026/5/29 19:09,2026-06-08T18:56,2026/06/10 10:56,"16,965",17368km,...,WELCOME5,MUM,12.945888,77.632509,76kmh,CARD,DL-1715906654,Major,Car returned in good condition,False
10,RES-00011,CUST-0280,CAR-078,NaN,No_Show,2026-02-21 8:53,2026/2/24 9:07,2026/2/26 2:16,"42,307","42,420",...,NEW10,Bengaluru,12.862574,77.581497,fast,-,DL-1969612434,Minor,Customer satisfied with ride,False
11,RES-00012,CUST-1975,CAR-071,SUV,Completed,10-06-2026 19:29,06/20/2026 19:29,2026/06/22 15:29,37002 km,36960km,...,NEW10,Bengaluru,12.921180,77.590590,35kmh,cash,DL-4087669203,Major,Low fuel warning observed,False
12,RES-00013,CUST-1637,CAR-114,NaN,Completed,2026-03-20 3:00,03/24/2026 3:00,26-03-2026 11:00,48024 km,48265km,...,NaN,Delhi,12.946229,77.649156,89kmh,NaN,DL-7430186207,NaN,Navigation system malfunction reported,False
13,RES-00014,CUST-1449,CAR-584,unknown,Completed,2026/2/11 4:01,2026/2/20 4:03,2026/2/23 1:04,37802,"38,209",...,SAVE50,chennai,12.908796,77.552898,21kmh,UPI,DL-9959447885,Major,Customer reported minor scratch on door,False
14,RES-00015,CUST-0793,CAR-463,SUV,No_Show,2026-05-02 20:48,2026-05-03T20:48,2026/05/04 7:48,35931,36389,...,NaN,blr,12.889304,77.591648,NaN,Debit Card,DL-3262834424,Minor,Customer requested early pickup,False
15,RES-00016,CUST-0225,CAR-202,Luxury,Cancelled,2026/5/17 1:15,2026-05-25T0:24,2026/5/26 4:02,"63,685",63644km,...,SAVE50,MUM,12.910854,77.626027,87kmh,NaN,DL-1236904688,Minor,Car returned in good condition,False
16,RES-00017,CUST-0507,CAR-136,unknown,Completed,2026-01-12 18:13,2026-01-21 18:13,2026/01/22 7:13,78899 km,79131km,...,WELCOME5,Mumbai,12.925445,77.616238,fast,netbanking,DL-7831334424,Major,NaN,False
17,RES-00018,CUST-1060,CAR-155,Hatchback,No_Show,2026/03/11 20:20,2026-03-19 20:20,2026/3/20 22:19,24271 km,24759,...,SAVE50,Bombay,12.942747,77.636700,fast,-,DL-3574178068,Major,Navigation system malfunction reported,False
18,RES-00019,CUST-1305,CAR-258,NaN,Completed,2026/02/22 22:34,03/04/2026 22:34,07-03-2026 12:34,"50,596","50,778",...,NEW10,unknown,12.922509,77.640096,40kmh,Wallet,DL-8651992307,NaN,Car returned in good condition,False
19,RES-00020,CUST-1337,CAR-564,unknown,Cancelled,2026-05-21T22:23,30-05-2026 22:23,01-06-2026 12:23,"38,038",38376km,...,WELCOME5,Mumbai,12.852637,77.613244,25 km/h,CASH,DL-6528407938,NaN,Customer reported minor scratch on door,False

In [7]:
df["Pickup_TS"] = df["Pickup_TS"].str.replace("/", "-", regex=False).str.replace("T", " ", regex=False)
df["Return_TS"] = df["Return_TS"].str.replace("/", "-", regex=False).str.replace("T", " ", regex=False)
df["Booking_TS"] = df["Booking_TS"].str.replace("/", "-", regex=False).str.replace("T", " ", regex=False)

In [8]:
df["Pickup_TS"] = pd.to_datetime(df["Pickup_TS"], format='mixed', dayfirst=True)
df["Return_TS"] = pd.to_datetime(df["Return_TS"], format='mixed', dayfirst=True)
df["Booking_TS"] = pd.to_datetime(df["Booking_TS"], format='mixed', dayfirst=True)

In [9]:
df.head(20)

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_Status,Booking_TS,Pickup_TS,Return_TS,Odo_Start,Odo_End,...,Promo_Code,City,GPS_Lat,GPS_Lon,Speed,Payment,Driver_License,Damage_Flag,Notes,Vehicle_ID_Invalid
0,RES-00001,CUST-1407,CAR-151,Luxury,Completed,2026-06-19 00:59:00,2026-06-27 00:59:00,2026-06-27 15:59:00,40729,40787,...,NaN,mumbai,12.948007,77.635873,NaN,netbanking,DL-1170728882,NaN,Navigation system malfunction reported,False
1,RES-00002,CUST-1555,CAR-538,SUV,Cancelled,2026-05-22 11:21:00,2026-05-27 11:21:00,2026-05-30 03:21:00,54220,"54,561",...,WELCOME5,delhi,12.889665,77.635561,134 km/h,card,DL-8720768076,Minor,AC performance slightly low,False
2,RES-00003,CUST-0100,CAR-118,Sedan,No_Show,2026-06-19 05:29:00,2026-06-22 05:29:00,2026-06-25 02:29:00,33021 km,33149km,...,WELCOME5,CHN,12.872257,77.623025,NaN,wallet,DL-2540682838,Major,Customer requested early pickup,False
3,RES-00004,CUST-1480,CAR-085,NaN,Completed,2026-04-06 22:10:00,2026-07-06 22:10:00,2026-10-06 19:01:00,76471,"76,415",...,NaN,MUM,12.856798,77.618630,fast,UPI,DL-3314017702,NaN,Vehicle returned late due to traffic,False
4,RES-00005,CUST-0696,CAR-292,unknown,Cancelled,2026-05-16 09:24:00,2026-05-23 09:24:00,2026-05-23 11:24:00,45940,"46,332",...,DISC20,CHN,12.852438,77.640421,NaN,upi,DL-4018623004,NaN,Vehicle returned late due to traffic,False
5,RES-00006,CUST-0361,CAR-211,Sedan,Completed,2026-09-03 03:03:00,2026-03-14 03:03:00,2026-03-16 01:03:00,"12,565",12894km,...,NaN,Mumbai,12.905509,77.618185,NaN,CARD,DL-5961002183,NaN,AC performance slightly low,False
6,RES-00007,CUST-1834,CAR-164,unknown,Cancelled,2025-12-28 00:00:00,2026-01-01 00:00:00,2026-02-01 21:17:00,19508 km,"19,429",...,NEW10,Bengaluru,12.927118,77.637018,NaN,upi,DL-2941631094,NaN,Car returned in good condition,False
7,RES-00008,CUST-1613,CAR-149,SUV,Cancelled,2026-01-25 00:00:00,2026-01-02 01:04:00,2026-02-02 11:00:00,17715 km,17862km,...,SAVE50,Mumbai,12.911117,77.557031,140,upi,DL-9482900041,Major,Vehicle returned late due to traffic,False
8,RES-00009,CUST-0331,CAR-018,Luxury,No_Show,2026-01-05 05:01:00,2026-09-05 05:01:00,2026-10-05 03:01:00,66473 km,66546km,...,WELCOME5,delhi,12.946923,77.571583,69 km/h,UPI,DL-3510206236,NaN,Customer reported minor scratch on door,False
9,RES-00010,CUST-0880,CAR-223,Sedan,Completed,2026-05-29 19:09:00,2026-08-06 18:56:00,2026-10-06 10:56:00,"16,965",17368km,...,WELCOME5,MUM,12.945888,77.632509,76kmh,CARD,DL-1715906654,Major,Car returned in good condition,False
10,RES-00011,CUST-0280,CAR-078,NaN,No_Show,2026-02-21 08:53:00,2026-02-24 09:07:00,2026-02-26 02:16:00,"42,307","42,420",...,NEW10,Bengaluru,12.862574,77.581497,fast,-,DL-1969612434,Minor,Customer satisfied with ride,False
11,RES-00012,CUST-1975,CAR-071,SUV,Completed,2026-06-10 19:29:00,2026-06-20 19:29:00,2026-06-22 15:29:00,37002 km,36960km,...,NEW10,Bengaluru,12.921180,77.590590,35kmh,cash,DL-4087669203,Major,Low fuel warning observed,False
12,RES-00013,CUST-1637,CAR-114,NaN,Completed,2026-03-20 03:00:00,2026-03-24 03:00:00,2026-03-26 11:00:00,48024 km,48265km,...,NaN,Delhi,12.946229,77.649156,89kmh,NaN,DL-7430186207,NaN,Navigation system malfunction reported,False
13,RES-00014,CUST-1449,CAR-584,unknown,Completed,2026-11-02 04:01:00,2026-02-20 04:03:00,2026-02-23 01:04:00,37802,"38,209",...,SAVE50,chennai,12.908796,77.552898,21kmh,UPI,DL-9959447885,Major,Customer reported minor scratch on door,False
14,RES-00015,CUST-0793,CAR-463,SUV,No_Show,2026-02-05 20:48:00,2026-03-05 20:48:00,2026-04-05 07:48:00,35931,36389,...,NaN,blr,12.889304,77.591648,NaN,Debit Card,DL-3262834424,Minor,Customer requested early pickup,False
15,RES-00016,CUST-0225,CAR-202,Luxury,Cancelled,2026-05-17 01:15:00,2026-05-25 00:24:00,2026-05-26 04:02:00,"63,685",63644km,...,SAVE50,MUM,12.910854,77.626027,87kmh,NaN,DL-1236904688,Minor,Car returned in good condition,False
16,RES-00017,CUST-0507,CAR-136,unknown,Completed,2026-12-01 18:13:00,2026-01-21 18:13:00,2026-01-22 07:13:00,78899 km,79131km,...,WELCOME5,Mumbai,12.925445,77.616238,fast,netbanking,DL-7831334424,Major,NaN,False
17,RES-00018,CUST-1060,CAR-155,Hatchback,No_Show,2026-11-03 20:20:00,2026-03-19 20:20:00,2026-03-20 22:19:00,24271 km,24759,...,SAVE50,Bombay,12.942747,77.636700,fast,-,DL-3574178068,Major,Navigation system malfunction reported,False
18,RES-00019,CUST-1305,CAR-258,NaN,Completed,2026-02-22 22:34:00,2026-04-03 22:34:00,2026-03-07 12:34:00,"50,596","50,778",...,NEW10,unknown,12.922509,77.640096,40kmh,Wallet,DL-8651992307,NaN,Car returned in good condition,False
19,RES-00020,CUST-1337,CAR-564,unknown,Cancelled,2026-05-21 22:23:00,2026-05-30 22:23:00,2026-06-01 12:23:00,"38,038",38376km,...,WELCOME5,Mumbai,12.852637,77.613244,25 km/h,CASH,DL-6528407938,NaN,Customer reported minor scratch on door,False

3. Odometer numeric extraction and unit unification (km)

In [10]:
def clean_odometer(value):

    if pd.isna(value):
        return pd.NA

    # convert to string
    value = str(value)

    # remove commas (12,519 → 12519)
    value = value.replace(",", "")

    # remove non-numeric characters (remove km etc.)
    value = re.sub(r'[^0-9.]', '', value)

    if value == "":
        return pd.NA

    return float(value)
# Apply function to both odometer columns
df['Odo_Start'] = df['Odo_Start'].apply(clean_odometer)
df['Odo_End'] = df['Odo_End'].apply(clean_odometer)

print(df[['Odo_Start','Odo_End']].head(10))

   Odo_Start  Odo_End
0    40729.0  40787.0
1    54220.0  54561.0
2    33021.0  33149.0
3    76471.0  76415.0
4    45940.0  46332.0
5    12565.0  12894.0
6    19508.0  19429.0
7    17715.0  17862.0
8    66473.0  66546.0
9    16965.0  17368.0

4. Fuel level normalization (50%→0.5)

In [11]:
# Remove % symbol
df["Fuel_Level"] = df["Fuel_Level"].astype(str).str.replace("%", "")

# Convert column to numeric
df["Fuel_Level"] = pd.to_numeric(df["Fuel_Level"], errors="coerce")

# Convert percentage values to fraction
df.loc[df["Fuel_Level"] > 1, "Fuel_Level"] = df["Fuel_Level"] / 100

df['Fuel_Level'].unique()

array([0.75, 0.5 , 0.1 , 0.3 , 1.  ,  nan, 0.25])

5. Rate parsing to numeric daily rate; currency normalization.

In [12]:
usd_to_inr = 92
eur_to_inr = 106

def clean_rate(val):

    if pd.isna(val):
        return pd.NA

    val = str(val).replace(",", "").strip()

    # USD values
    if "USD" in val or "$" in val:
        num = re.findall(r'\d+', val)
        if num:
            return int(num[0]) * usd_to_inr

    # EURO values
    if "EUR" in val or "€" in val:
        num = re.findall(r'\d+', val)
        if num:
            return int(num[0]) * eur_to_inr

    # INR values
    num = re.findall(r'\d+', val)
    if num:
        return int(num[0])

    return pd.NA


df["Rate"] = df["Rate"].apply(clean_rate)

In [13]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
df.head(20)

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_Status,Booking_TS,Pickup_TS,Return_TS,Odo_Start,Odo_End,Fuel_Level,Rate,Promo_Code,City,GPS_Lat,GPS_Lon,Speed,Payment,Driver_License,Damage_Flag,Notes,Vehicle_ID_Invalid
0,RES-00001,CUST-1407,CAR-151,Luxury,Completed,2026-06-19 00:59:00,2026-06-27 00:59:00,2026-06-27 15:59:00,40729.0,40787.0,0.75,2300,NaN,mumbai,12.948007,77.635873,NaN,netbanking,DL-1170728882,NaN,Navigation system malfunction reported,False
1,RES-00002,CUST-1555,CAR-538,SUV,Cancelled,2026-05-22 11:21:00,2026-05-27 11:21:00,2026-05-30 03:21:00,54220.0,54561.0,0.50,1840,WELCOME5,delhi,12.889665,77.635561,134 km/h,card,DL-8720768076,Minor,AC performance slightly low,False
2,RES-00003,CUST-0100,CAR-118,Sedan,No_Show,2026-06-19 05:29:00,2026-06-22 05:29:00,2026-06-25 02:29:00,33021.0,33149.0,0.10,2300,WELCOME5,CHN,12.872257,77.623025,NaN,wallet,DL-2540682838,Major,Customer requested early pickup,False
3,RES-00004,CUST-1480,CAR-085,NaN,Completed,2026-04-06 22:10:00,2026-07-06 22:10:00,2026-10-06 19:01:00,76471.0,76415.0,0.10,1800,NaN,MUM,12.856798,77.618630,fast,UPI,DL-3314017702,NaN,Vehicle returned late due to traffic,False
4,RES-00005,CUST-0696,CAR-292,unknown,Cancelled,2026-05-16 09:24:00,2026-05-23 09:24:00,2026-05-23 11:24:00,45940.0,46332.0,0.30,2000,DISC20,CHN,12.852438,77.640421,NaN,upi,DL-4018623004,NaN,Vehicle returned late due to traffic,False
5,RES-00006,CUST-0361,CAR-211,Sedan,Completed,2026-09-03 03:03:00,2026-03-14 03:03:00,2026-03-16 01:03:00,12565.0,12894.0,0.75,2500,NaN,Mumbai,12.905509,77.618185,NaN,CARD,DL-5961002183,NaN,AC performance slightly low,False
6,RES-00007,CUST-1834,CAR-164,unknown,Cancelled,2025-12-28 00:00:00,2026-01-01 00:00:00,2026-02-01 21:17:00,19508.0,19429.0,0.50,1840,NEW10,Bengaluru,12.927118,77.637018,NaN,upi,DL-2941631094,NaN,Car returned in good condition,False
7,RES-00008,CUST-1613,CAR-149,SUV,Cancelled,2026-01-25 00:00:00,2026-01-02 01:04:00,2026-02-02 11:00:00,17715.0,17862.0,0.75,1840,SAVE50,Mumbai,12.911117,77.557031,140,upi,DL-9482900041,Major,Vehicle returned late due to traffic,False
8,RES-00009,CUST-0331,CAR-018,Luxury,No_Show,2026-01-05 05:01:00,2026-09-05 05:01:00,2026-10-05 03:01:00,66473.0,66546.0,0.50,<NA>,WELCOME5,delhi,12.946923,77.571583,69 km/h,UPI,DL-3510206236,NaN,Customer reported minor scratch on door,False
9,RES-00010,CUST-0880,CAR-223,Sedan,Completed,2026-05-29 19:09:00,2026-08-06 18:56:00,2026-10-06 10:56:00,16965.0,17368.0,0.75,1500,WELCOME5,MUM,12.945888,77.632509,76kmh,CARD,DL-1715906654,Major,Car returned in good condition,False
10,RES-00011,CUST-0280,CAR-078,NaN,No_Show,2026-02-21 08:53:00,2026-02-24 09:07:00,2026-02-26 02:16:00,42307.0,42420.0,0.75,1800,NEW10,Bengaluru,12.862574,77.581497,fast,-,DL-1969612434,Minor,Customer satisfied with ride,False
11,RES-00012,CUST-1975,CAR-071,SUV,Completed,2026-06-10 19:29:00,2026-06-20 19:29:00,2026-06-22 15:29:00,37002.0,36960.0,0.75,2000,NEW10,Bengaluru,12.921180,77.590590,35kmh,cash,DL-4087669203,Major,Low fuel warning observed,False
12,RES-00013,CUST-1637,CAR-114,NaN,Completed,2026-03-20 03:00:00,2026-03-24 03:00:00,2026-03-26 11:00:00,48024.0,48265.0,1.00,1500,NaN,Delhi,12.946229,77.649156,89kmh,NaN,DL-7430186207,NaN,Navigation system malfunction reported,False
13,RES-00014,CUST-1449,CAR-584,unknown,Completed,2026-11-02 04:01:00,2026-02-20 04:03:00,2026-02-23 01:04:00,37802.0,38209.0,0.75,2300,SAVE50,chennai,12.908796,77.552898,21kmh,UPI,DL-9959447885,Major,Customer reported minor scratch on door,False
14,RES-00015,CUST-0793,CAR-463,SUV,No_Show,2026-02-05 20:48:00,2026-03-05 20:48:00,2026-04-05 07:48:00,35931.0,36389.0,0.50,2000,NaN,blr,12.889304,77.591648,NaN,Debit Card,DL-3262834424,Minor,Customer requested early pickup,False
15,RES-00016,CUST-0225,CAR-202,Luxury,Cancelled,2026-05-17 01:15:00,2026-05-25 00:24:00,2026-05-26 04:02:00,63685.0,63644.0,NaN,2300,SAVE50,MUM,12.910854,77.626027,87kmh,NaN,DL-1236904688,Minor,Car returned in good condition,False
16,RES-00017,CUST-0507,CAR-136,unknown,Completed,2026-12-01 18:13:00,2026-01-21 18:13:00,2026-01-22 07:13:00,78899.0,79131.0,0.50,1500,WELCOME5,Mumbai,12.925445,77.616238,fast,netbanking,DL-7831334424,Major,NaN,False
17,RES-00018,CUST-1060,CAR-155,Hatchback,No_Show,2026-11-03 20:20:00,2026-03-19 20:20:00,2026-03-20 22:19:00,24271.0,24759.0,0.50,1500,SAVE50,Bombay,12.942747,77.636700,fast,-,DL-3574178068,Major,Navigation system malfunction reported,False
18,RES-00019,CUST-1305,CAR-258,NaN,Completed,2026-02-22 22:34:00,2026-04-03 22:34:00,2026-03-07 12:34:00,50596.0,50778.0,0.50,1500,NEW10,unknown,12.922509,77.640096,40kmh,Wallet,DL-8651992307,NaN,Car returned in good condition,False
19,RES-00020,CUST-1337,CAR-564,unknown,Cancelled,2026-05-21 22:23:00,2026-05-30 22:23:00,2026-06-01 12:23:00,38038.0,38376.0,1.00,1800,WELCOME5,Mumbai,12.852637,77.613244,25 km/h,CASH,DL-6528407938,NaN,Customer reported minor scratch on door,False

6. City normalization to canonical names.

In [14]:
# Check unique city values before cleaning
print("Cities BEFORE cleaning:")
print(df["City"].unique())

# Step 1: Remove spaces
df["City"] = df["City"].str.strip()

# Step 2: Convert everything to lowercase
df["City"] = df["City"].str.lower()

# Step 3: Replace unknown and missing values with NA
df["City"] = df["City"].replace("unknown", pd.NA)

# Step 4: Map inconsistent names to standard names
city_mapping = {
    "blr": "bengaluru",
    "bangalore": "bengaluru",
    "bengaluru": "bengaluru",

    "mum": "mumbai",
    "bombay": "mumbai",
    "mumbai": "mumbai",

    "del": "delhi",
    "delhi": "delhi",
    "new delhi": "delhi",

    "chn": "chennai",
    "chennai": "chennai",

}

df["City"] = df["City"].replace(city_mapping)

# Step 5: Convert to title case
df["City"] = df["City"].str.title()

df["City"].value_counts()

# Check unique city values after cleaning
print("Cities AFTER cleaning:")
print(df["City"].unique())

Cities BEFORE cleaning:
<StringArray>
[   'mumbai',     'delhi',       'CHN',       'MUM',    'Mumbai', 'Bengaluru',
     'Delhi',   'chennai',       'blr',    'Bombay',   'unknown', 'bangalore',
   'Chennai', 'New Delhi',         nan,       'BLR',     'DELHI']
Length: 17, dtype: str
Cities AFTER cleaning:
<StringArray>
['Mumbai', 'Delhi', 'Chennai', 'Bengaluru', nan]
Length: 5, dtype: str

7. Duplicate reservation dedup (same ID).

In [15]:
print(f"Duplicate Reservation_IDs: {df['Reservation_ID'].duplicated().sum()}")
df = df.drop_duplicates(subset='Reservation_ID', keep='first')
print(f"Shape after dedup: {df.shape}")

Duplicate Reservation_IDs: 473
Shape after dedup: (4527, 22)

8. Return before pickup rule validation.

In [16]:
swap_mask = df["Return_TS"] < df["Pickup_TS"]

df.loc[swap_mask, ["Pickup_TS","Return_TS"]] = \
df.loc[swap_mask, ["Return_TS","Pickup_TS"]].values

In [17]:
df["Duration_Hours"] = (df["Return_TS"] - df["Pickup_TS"]).dt.total_seconds() / 3600

In [18]:
invalid_duration = df[df["Duration_Hours"] < 0]

In [19]:
equal_mask = df["Return_TS"] == df["Pickup_TS"]

In [20]:
df.loc[equal_mask, ["Pickup_TS", "Return_TS"]] = pd.NaT

In [21]:
print(invalid_duration)

Empty DataFrame
Columns: [Reservation_ID, Customer_ID, Vehicle_ID, Vehicle_Class, Booking_Status, Booking_TS, Pickup_TS, Return_TS, Odo_Start, Odo_End, Fuel_Level, Rate, Promo_Code, City, GPS_Lat, GPS_Lon, Speed, Payment, Driver_License, Damage_Flag, Notes, Vehicle_ID_Invalid, Duration_Hours]
Index: []

In [22]:
df.head(20)

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_Status,Booking_TS,Pickup_TS,Return_TS,Odo_Start,Odo_End,Fuel_Level,Rate,Promo_Code,City,GPS_Lat,GPS_Lon,Speed,Payment,Driver_License,Damage_Flag,Notes,Vehicle_ID_Invalid,Duration_Hours
0,RES-00001,CUST-1407,CAR-151,Luxury,Completed,2026-06-19 00:59:00,2026-06-27 00:59:00,2026-06-27 15:59:00,40729.0,40787.0,0.75,2300,NaN,Mumbai,12.948007,77.635873,NaN,netbanking,DL-1170728882,NaN,Navigation system malfunction reported,False,15.000000
1,RES-00002,CUST-1555,CAR-538,SUV,Cancelled,2026-05-22 11:21:00,2026-05-27 11:21:00,2026-05-30 03:21:00,54220.0,54561.0,0.50,1840,WELCOME5,Delhi,12.889665,77.635561,134 km/h,card,DL-8720768076,Minor,AC performance slightly low,False,64.000000
2,RES-00003,CUST-0100,CAR-118,Sedan,No_Show,2026-06-19 05:29:00,2026-06-22 05:29:00,2026-06-25 02:29:00,33021.0,33149.0,0.10,2300,WELCOME5,Chennai,12.872257,77.623025,NaN,wallet,DL-2540682838,Major,Customer requested early pickup,False,69.000000
3,RES-00004,CUST-1480,CAR-085,NaN,Completed,2026-04-06 22:10:00,2026-07-06 22:10:00,2026-10-06 19:01:00,76471.0,76415.0,0.10,1800,NaN,Mumbai,12.856798,77.618630,fast,UPI,DL-3314017702,NaN,Vehicle returned late due to traffic,False,2204.850000
4,RES-00005,CUST-0696,CAR-292,unknown,Cancelled,2026-05-16 09:24:00,2026-05-23 09:24:00,2026-05-23 11:24:00,45940.0,46332.0,0.30,2000,DISC20,Chennai,12.852438,77.640421,NaN,upi,DL-4018623004,NaN,Vehicle returned late due to traffic,False,2.000000
5,RES-00006,CUST-0361,CAR-211,Sedan,Completed,2026-09-03 03:03:00,2026-03-14 03:03:00,2026-03-16 01:03:00,12565.0,12894.0,0.75,2500,NaN,Mumbai,12.905509,77.618185,NaN,CARD,DL-5961002183,NaN,AC performance slightly low,False,46.000000
6,RES-00007,CUST-1834,CAR-164,unknown,Cancelled,2025-12-28 00:00:00,2026-01-01 00:00:00,2026-02-01 21:17:00,19508.0,19429.0,0.50,1840,NEW10,Bengaluru,12.927118,77.637018,NaN,upi,DL-2941631094,NaN,Car returned in good condition,False,765.283333
7,RES-00008,CUST-1613,CAR-149,SUV,Cancelled,2026-01-25 00:00:00,2026-01-02 01:04:00,2026-02-02 11:00:00,17715.0,17862.0,0.75,1840,SAVE50,Mumbai,12.911117,77.557031,140,upi,DL-9482900041,Major,Vehicle returned late due to traffic,False,753.933333
8,RES-00009,CUST-0331,CAR-018,Luxury,No_Show,2026-01-05 05:01:00,2026-09-05 05:01:00,2026-10-05 03:01:00,66473.0,66546.0,0.50,<NA>,WELCOME5,Delhi,12.946923,77.571583,69 km/h,UPI,DL-3510206236,NaN,Customer reported minor scratch on door,False,718.000000
9,RES-00010,CUST-0880,CAR-223,Sedan,Completed,2026-05-29 19:09:00,2026-08-06 18:56:00,2026-10-06 10:56:00,16965.0,17368.0,0.75,1500,WELCOME5,Mumbai,12.945888,77.632509,76kmh,CARD,DL-1715906654,Major,Car returned in good condition,False,1456.000000
10,RES-00011,CUST-0280,CAR-078,NaN,No_Show,2026-02-21 08:53:00,2026-02-24 09:07:00,2026-02-26 02:16:00,42307.0,42420.0,0.75,1800,NEW10,Bengaluru,12.862574,77.581497,fast,-,DL-1969612434,Minor,Customer satisfied with ride,False,41.150000
11,RES-00012,CUST-1975,CAR-071,SUV,Completed,2026-06-10 19:29:00,2026-06-20 19:29:00,2026-06-22 15:29:00,37002.0,36960.0,0.75,2000,NEW10,Bengaluru,12.921180,77.590590,35kmh,cash,DL-4087669203,Major,Low fuel warning observed,False,44.000000
12,RES-00013,CUST-1637,CAR-114,NaN,Completed,2026-03-20 03:00:00,2026-03-24 03:00:00,2026-03-26 11:00:00,48024.0,48265.0,1.00,1500,NaN,Delhi,12.946229,77.649156,89kmh,NaN,DL-7430186207,NaN,Navigation system malfunction reported,False,56.000000
13,RES-00014,CUST-1449,CAR-584,unknown,Completed,2026-11-02 04:01:00,2026-02-20 04:03:00,2026-02-23 01:04:00,37802.0,38209.0,0.75,2300,SAVE50,Chennai,12.908796,77.552898,21kmh,UPI,DL-9959447885,Major,Customer reported minor scratch on door,False,69.016667
14,RES-00015,CUST-0793,CAR-463,SUV,No_Show,2026-02-05 20:48:00,2026-03-05 20:48:00,2026-04-05 07:48:00,35931.0,36389.0,0.50,2000,NaN,Bengaluru,12.889304,77.591648,NaN,Debit Card,DL-3262834424,Minor,Customer requested early pickup,False,731.000000
15,RES-00016,CUST-0225,CAR-202,Luxury,Cancelled,2026-05-17 01:15:00,2026-05-25 00:24:00,2026-05-26 04:02:00,63685.0,63644.0,NaN,2300,SAVE50,Mumbai,12.910854,77.626027,87kmh,NaN,DL-1236904688,Minor,Car returned in good condition,False,27.633333
16,RES-00017,CUST-0507,CAR-136,unknown,Completed,2026-12-01 18:13:00,2026-01-21 18:13:00,2026-01-22 07:13:00,78899.0,79131.0,0.50,1500,WELCOME5,Mumbai,12.925445,77.616238,fast,netbanking,DL-7831334424,Major,NaN,False,13.000000
17,RES-00018,CUST-1060,CAR-155,Hatchback,No_Show,2026-11-03 20:20:00,2026-03-19 20:20:00,2026-03-20 22:19:00,24271.0,24759.0,0.50,1500,SAVE50,Mumbai,12.942747,77.636700,fast,-,DL-3574178068,Major,Navigation system malfunction reported,False,25.983333
18,RES-00019,CUST-1305,CAR-258,NaN,Completed,2026-02-22 22:34:00,2026-03-07 12:34:00,2026-04-03 22:34:00,50596.0,50778.0,0.50,1500,NEW10,NaN,12.922509,77.640096,40kmh,Wallet,DL-8651992307,NaN,Car returned in good condition,False,658.000000
19,RES-00020,CUST-1337,CAR-564,unknown,Cancelled,2026-05-21 22:23:00,2026-05-30 22:23:00,2026-06-01 12:23:00,38038.0,38376.0,1.00,1800,WELCOME5,Mumbai,12.852637,77.613244,25 km/h,CASH,DL-6528407938,NaN,Customer reported minor scratch on door,False,38.000000

9. Payment method standardization (UPI/CARD/CASH/WALLET).

In [23]:
df["Payment"] = df["Payment"].astype(str).str.lower().str.strip()

payment_dict = {
    "upi": "UPI",
    
    "credit card": "CARD",
    "debit card": "CARD",
    "card": "CARD",
    "netbanking": "CARD",
    
    "cash": "CASH",
    
    "wallet": "WALLET",
    
    "-": pd.NA,
    "nan": pd.NA
}

df["Payment"] = df["Payment"].replace(payment_dict)
print(df["Payment"].unique())

<StringArray>
['CARD', 'WALLET', 'UPI', nan, 'CASH']
Length: 5, dtype: str

10. Mileage sanity check (End ≥ Start)

In [24]:
mileage_check = df[['Reservation_ID','Odo_Start','Odo_End']].copy()

# Swap Odo_Start and Odo_End where End < Start (likely data entry error)
odo_swap_mask = df['Odo_End'] < df['Odo_Start']
df.loc[odo_swap_mask, ['Odo_Start', 'Odo_End']] = df.loc[odo_swap_mask, ['Odo_End', 'Odo_Start']].values
print(f"Swapped Odo_Start/Odo_End for {odo_swap_mask.sum()} rows")

# Verify no invalid mileages remain
mileage_check = df[['Reservation_ID','Odo_Start','Odo_End']].copy()
mileage_check['Mileage_Valid'] = mileage_check['Odo_End'] >= mileage_check['Odo_Start']
print(f"Invalid mileages remaining: {(~mileage_check['Mileage_Valid']).sum()}")
mileage_check.head(10)

Swapped Odo_Start/Odo_End for 759 rows
Invalid mileages remaining: 0

  Reservation_ID  Odo_Start  Odo_End  Mileage_Valid
0      RES-00001    40729.0  40787.0           True
1      RES-00002    54220.0  54561.0           True
2      RES-00003    33021.0  33149.0           True
3      RES-00004    76415.0  76471.0           True
4      RES-00005    45940.0  46332.0           True
5      RES-00006    12565.0  12894.0           True
6      RES-00007    19429.0  19508.0           True
7      RES-00008    17715.0  17862.0           True
8      RES-00009    66473.0  66546.0           True
9      RES-00010    16965.0  17368.0           True

11. Refueling event detection vs fuel change and distance.

In [25]:
# Step 1: Normalize Fuel_Level (re-normalize in case of any remaining % values)
df["Fuel_Level"] = df["Fuel_Level"].astype(str).str.replace("%", "", regex=False)
df["Fuel_Level"] = pd.to_numeric(df["Fuel_Level"], errors="coerce")

# Convert percentage values to fraction
df.loc[df["Fuel_Level"] > 1, "Fuel_Level"] = df["Fuel_Level"] / 100


# Step 2: Create temporary dataframe
Refuel_Event = df[["Reservation_ID", "Vehicle_ID", "Odo_Start", "Odo_End", "Fuel_Level"]].copy()


# Step 3: Remove invalid odometer rows (sanity check from UC10)
Refuel_Event = Refuel_Event[Refuel_Event["Odo_End"] >= Refuel_Event["Odo_Start"]]


# Step 4: Calculate distance driven
Refuel_Event["Distance_Driven"] = Refuel_Event["Odo_End"] - Refuel_Event["Odo_Start"]


# Step 5: Detect refuel events (grouped by Vehicle_ID)
Refuel_Event = Refuel_Event.sort_values(["Vehicle_ID", "Odo_Start"])
Refuel_Event["Refuel_Event"] = Refuel_Event.groupby("Vehicle_ID")["Fuel_Level"].diff() > 0

Refuel_Event["Refuel_Event"] = Refuel_Event["Refuel_Event"].map(
    {True: "Refueled", False: "No Refuel"}
)


# Step 6: Replace NaN with "NA" for display
Refuel_Event = Refuel_Event.fillna(pd.NA)


# Step 7: Display
Refuel_Event.head(10)

,Reservation_ID,Vehicle_ID,Odo_Start,Odo_End,Fuel_Level,Distance_Driven,Refuel_Event
556,RES-00557,CAR-001,10329.0,10576.0,1.00,247.0,No Refuel
3130,RES-03131,CAR-001,18654.0,18897.0,0.75,243.0,No Refuel
404,RES-00405,CAR-001,24970.0,25116.0,0.30,146.0,No Refuel
2333,RES-02334,CAR-001,31640.0,31875.0,1.00,235.0,Refueled
1237,RES-01238,CAR-001,62535.0,62932.0,1.00,397.0,No Refuel
2803,RES-02804,CAR-001,70047.0,70145.0,0.50,98.0,No Refuel
1252,RES-01253,CAR-002,14324.0,14390.0,0.75,66.0,No Refuel
2193,RES-02194,CAR-002,14417.0,14567.0,0.30,150.0,No Refuel
58,RES-00059,CAR-002,33502.0,33599.0,0.25,97.0,No Refuel
522,RES-00523,CAR-002,45706.0,45834.0,1.00,128.0,Refueled

12. Vehicle availability overlap checks.

In [26]:
df = df.sort_values(['Vehicle_ID','Pickup_TS'])
df['Prev_Return'] = df.groupby('Vehicle_ID')['Return_TS'].shift(1)
df['Overlap_Flag'] = df['Pickup_TS'] < df['Prev_Return']
overlaps = df[df['Overlap_Flag'] == True]
overlaps
df = df[df['Overlap_Flag'] == False]
df['Overlap_Flag'].sum()

np.int64(0)

13. Damage / Incident Log Linkage to Reservation

In [27]:
#inspect
df[['Reservation_ID','Vehicle_ID','Customer_ID','Damage_Flag','Notes']].head()

#Extract rows where damage was reported
damage_logs = df[
    df['Damage_Flag'].notna() &
    (df['Damage_Flag'] != 'None')
]


#Create a separate incident log dataset
incident_log = damage_logs[[
    'Reservation_ID',
    'Vehicle_ID',
    'Customer_ID',
    'Damage_Flag',
    'Notes'
]].copy()


#Check for records where damage is flagged but notes are missing
missing_notes = incident_log[
    incident_log['Notes'].isna() |
    (incident_log['Notes'].str.strip() == "")
]


print("Damage incidents missing description:", len(missing_notes))


#Detect possible damage mentioned in notes but flag is 'None'
possible_damage = df[
    (df['Damage_Flag'] == 'None') &
    (df['Notes'].str.contains('damage|scratch|dent|crack', case=False, na=False))
]


print("Possible misclassified incidents:", len(possible_damage))


#Display the final incident log dataset
incident_log.head(15)
df['Notes'].unique()

Damage incidents missing description: 352
Possible misclassified incidents: 0

<StringArray>
['Customer reported minor scratch on door',
            'Customer satisfied with ride',
                                       nan,
          'Car returned in good condition',
         'Tyre pressure alert during trip',
  'Navigation system malfunction reported',
         'Customer requested early pickup',
               'Low fuel warning observed',
    'Vehicle returned late due to traffic',
             'AC performance slightly low',
              'Interior cleaning required']
Length: 11, dtype: str

14. Driver license masking and validation (if present).

In [28]:
#validation
def validate_license(x):
    if pd.isna(x):
        return None
    
    x = str(x)
    
    if re.match(r"DL-\d{10}$", x):
        return x
    else:
        return None

df["Driver_License"] = df["Driver_License"].apply(validate_license)

In [29]:
#masking
def mask_license(x):
    if pd.isna(x):
        return None
    
    return x[:7] + "XXXXXX"

df["Driver_License"] = df["Driver_License"].apply(mask_license)

15. Promo/coupon code validation & expiry checks.

In [30]:
# convert pickup timestamp
df["Pickup_TS"] = pd.to_datetime(df["Pickup_TS"], errors="coerce")

# promo expiry dictionary
promo_expiry = {
    "NEW10": "2026-03-31",
    "DISC20": "2026-02-28",
    "SAVE50": "2026-06-30",
    "WELCOME5": "2026-01-31"
}

# convert expiry values to datetime
promo_expiry = {k: pd.to_datetime(v) for k, v in promo_expiry.items()}

# map expiry date to dataset
df["Promo_Expiry"] = df["Promo_Code"].map(promo_expiry)

df["Promo_Status"] = "Valid"

# invalid promo codes
df.loc[df["Promo_Code"].notna() & df["Promo_Expiry"].isna(), "Promo_Status"] = "Invalid_Code"

# expired promo codes
df.loc[(df["Promo_Expiry"].notna()) & (df["Pickup_TS"] > df["Promo_Expiry"]), "Promo_Status"] = "Expired"

In [31]:
df.head(30)

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_Status,Booking_TS,Pickup_TS,Return_TS,Odo_Start,Odo_End,Fuel_Level,Rate,Promo_Code,City,GPS_Lat,GPS_Lon,Speed,Payment,Driver_License,Damage_Flag,Notes,Vehicle_ID_Invalid,Duration_Hours,Prev_Return,Overlap_Flag,Promo_Expiry,Promo_Status
1237,RES-01238,CUST-0446,CAR-001,Hatchback,No_Show,2026-08-01 04:23:00,2026-01-15 04:23:00,2026-01-18 03:23:00,62535.0,62932.0,1.00,1500,NEW10,Bengaluru,12.860193,77.567523,114kmh,NaN,DL-8955XXXXXX,Minor,Customer reported minor scratch on door,False,71.000000,NaT,False,2026-03-31,Valid
3130,RES-03131,CUST-0257,CAR-001,NaN,Cancelled,2026-01-22 12:18:00,2026-01-23 12:18:00,2026-01-25 02:18:00,18654.0,18897.0,0.75,1800,WELCOME5,Bengaluru,12.879495,77.649480,119 km/h,CARD,DL-4156XXXXXX,NaN,Customer satisfied with ride,False,38.000000,2026-01-18 03:23:00,False,2026-01-31,Valid
556,RES-00557,CUST-0029,CAR-001,Hatchback,Completed,2026-02-14 06:33:00,2026-02-18 06:33:00,2026-02-19 08:33:00,10329.0,10576.0,1.00,1500,NEW10,Delhi,12.854050,77.569744,117kmh,CARD,DL-6241XXXXXX,NaN,NaN,False,26.000000,2026-01-25 02:18:00,False,2026-03-31,Valid
404,RES-00405,CUST-0694,CAR-001,Luxury,Completed,2026-04-30 14:16:00,2026-04-05 14:16:00,2026-05-05 22:16:00,24970.0,25116.0,0.30,1800,NEW10,Mumbai,12.913531,77.604304,73kmh,CASH,DL-5092XXXXXX,NaN,Car returned in good condition,False,728.000000,2026-02-19 08:33:00,False,2026-03-31,Expired
2803,RES-02804,CUST-0532,CAR-001,Sedan,Completed,2026-06-18 08:08:00,2026-06-23 08:08:00,2026-06-25 05:14:00,70047.0,70145.0,0.50,2500,WELCOME5,Delhi,12.941481,77.566673,112 km/h,CARD,DL-9286XXXXXX,Major,Tyre pressure alert during trip,False,45.100000,2026-04-21 03:51:00,False,2026-01-31,Expired
522,RES-00523,CUST-0353,CAR-002,unknown,Cancelled,2025-12-30 01:24:00,2026-01-02 01:24:00,2026-02-01 02:00:00,45706.0,45834.0,1.00,<NA>,DISC20,Delhi,12.935368,77.617963,NaN,CARD,DL-2564XXXXXX,Minor,Navigation system malfunction reported,False,720.600000,NaT,False,2026-02-28,Valid
2166,RES-02167,CUST-0079,CAR-002,Sedan,Completed,2026-07-03 11:55:00,2026-03-13 11:55:00,2026-03-15 08:55:00,69759.0,70035.0,0.75,1800,SAVE50,Mumbai,12.932531,77.566649,62 km/h,NaN,DL-3466XXXXXX,Major,Customer requested early pickup,False,45.000000,2026-01-23 06:10:00,False,2026-06-30,Valid
58,RES-00059,CUST-1731,CAR-002,Sedan,No_Show,2026-05-15 13:03:00,2026-05-23 11:09:00,2026-05-23 13:11:00,33502.0,33599.0,0.25,1500,DISC20,Chennai,12.871327,77.629466,fast,CARD,DL-8914XXXXXX,NaN,Low fuel warning observed,False,2.033333,2026-03-15 08:55:00,False,2026-02-28,Expired
2193,RES-02194,CUST-1443,CAR-002,Sedan,Completed,2026-09-06 13:51:00,2026-06-14 13:51:00,2026-06-15 10:51:00,14417.0,14567.0,0.30,1500,SAVE50,Bengaluru,12.866360,77.553843,fast,CARD,DL-5895XXXXXX,Minor,Customer satisfied with ride,False,21.000000,2026-05-23 13:11:00,False,2026-06-30,Valid
2957,RES-02958,CUST-0352,CAR-002,unknown,No_Show,2026-06-27 10:27:00,2026-06-28 10:27:00,2026-06-30 13:27:00,48330.0,48514.0,0.25,2000,NaN,Delhi,12.858027,77.566427,NaN,NaN,DL-1337XXXXXX,Minor,Vehicle returned late due to traffic,False,51.000000,2026-06-15 10:51:00,False,NaT,Valid
1252,RES-01253,CUST-1418,CAR-002,NaN,Completed,2026-08-02 11:46:00,2026-12-02 11:46:00,2026-12-02 15:07:00,14324.0,14390.0,0.75,2000,WELCOME5,Mumbai,12.920225,77.599916,fast,CARD,DL-2409XXXXXX,Major,NaN,False,3.350000,2026-06-30 13:27:00,False,2026-01-31,Expired
4525,RES-04526,CUST-1762,CAR-003,NaN,Cancelled,2025-12-30 01:15:00,2026-01-01 01:14:00,2026-01-01 08:38:00,58785.0,58823.0,0.30,1500,NEW10,Chennai,12.860315,77.627091,119kmh,CARD,DL-2710XXXXXX,NaN,AC performance slightly low,False,7.400000,NaT,False,2026-03-31,Valid
407,RES-00408,CUST-0733,CAR-003,SUV,Completed,2026-05-01 14:10:00,2026-01-06 14:10:00,2026-09-01 02:10:00,13333.0,13715.0,0.25,1840,NaN,Mumbai,12.897086,77.586456,fast,CARD,DL-1700XXXXXX,Minor,Car returned in good condition,False,5700.000000,2026-01-01 08:38:00,False,NaT,Valid
2516,RES-02517,CUST-1887,CAR-003,Hatchback,No_Show,2026-10-06 21:03:00,2026-06-15 21:03:00,2026-06-16 20:03:00,75428.0,75676.0,1.00,1800,NEW10,Bengaluru,12.873920,77.634301,79 km/h,CARD,DL-5182XXXXXX,Major,NaN,False,23.000000,2026-05-22 10:38:00,False,2026-03-31,Expired
317,RES-00318,CUST-1433,CAR-003,unknown,Completed,2026-06-06 04:07:00,2026-07-06 03:49:00,2026-08-06 02:49:00,76205.0,76270.0,0.10,2000,NaN,Mumbai,12.931989,77.635517,41 km/h,UPI,DL-9683XXXXXX,Minor,Vehicle returned late due to traffic,False,743.000000,2026-06-16 20:03:00,False,NaT,Valid
1223,RES-01224,CUST-0138,CAR-005,Luxury,Cancelled,2026-01-29 19:50:00,2026-03-02 19:50:00,2026-05-02 01:13:00,46275.0,46579.0,1.00,1500,WELCOME5,Mumbai,12.923462,77.567919,NaN,WALLET,DL-6169XXXXXX,NaN,Interior cleaning required,False,1445.383333,NaT,False,2026-01-31,Expired
1135,RES-01136,CUST-0412,CAR-005,Luxury,Cancelled,2026-05-03 13:47:00,2026-04-05 13:47:00,2026-05-05 22:47:00,53241.0,53441.0,1.00,2300,NEW10,Mumbai,12.927485,77.620431,NaN,CARD,DL-6912XXXXXX,NaN,Vehicle returned late due to traffic,False,729.000000,2026-03-27 13:33:00,False,2026-03-31,Expired
932,RES-00933,CUST-0349,CAR-005,NaN,No_Show,2026-01-05 09:11:00,2026-05-10 09:11:00,2026-11-05 02:04:00,28723.0,28757.0,0.30,2300,SAVE50,Delhi,12.850752,77.587336,92 km/h,CASH,DL-6538XXXXXX,Major,Customer reported minor scratch on door,False,4288.883333,2026-04-23 00:50:00,False,2026-06-30,Valid
2180,RES-02181,CUST-1418,CAR-006,SUV,Completed,2026-03-30 19:40:00,2026-01-04 20:14:00,2026-02-04 13:40:00,75915.0,75928.0,0.75,<NA>,NaN,Chennai,12.853717,77.579892,99,CARD,DL-2409XXXXXX,Minor,AC performance slightly low,False,737.433333,NaT,False,NaT,Valid
257,RES-00258,CUST-0805,CAR-006,SUV,No_Show,2026-02-17 08:06:00,2026-02-23 08:06:00,2026-02-24 10:06:00,74128.0,74246.0,NaN,2000,DISC20,Bengaluru,12.902855,77.595877,25,NaN,DL-1739XXXXXX,Major,Car returned in good condition,False,26.000000,2026-02-16 08:37:00,False,2026-02-28,Valid
3039,RES-03040,CUST-1438,CAR-006,Hatchback,No_Show,2026-06-03 07:31:00,2026-03-13 07:31:00,2026-03-14 09:31:00,79257.0,79483.0,1.00,1800,NaN,Bengaluru,12.868764,77.551627,109kmh,CARD,DL-5174XXXXXX,Minor,Customer reported minor scratch on door,False,26.000000,2026-02-24 10:06:00,False,NaT,Valid
2587,RES-02588,CUST-0532,CAR-006,SUV,Cancelled,2026-03-21 15:28:00,2026-03-22 16:12:00,2026-03-24 23:28:00,57039.0,57386.0,0.50,2500,NEW10,NaN,12.858910,77.592404,fast,CARD,DL-9286XXXXXX,Major,Customer reported minor scratch on door,False,55.266667,2026-03-14 09:31:00,False,2026-03-31,Valid
2977,RES-02978,CUST-0581,CAR-006,NaN,No_Show,2026-03-31 22:52:00,2026-04-04 22:52:00,2026-04-06 07:52:00,72350.0,72406.0,NaN,<NA>,SAVE50,Mumbai,12.896631,77.611986,104 km/h,CASH,DL-5220XXXXXX,Major,AC performance slightly low,False,33.000000,2026-03-24 23:28:00,False,2026-06-30,Valid
635,RES-00636,CUST-0277,CAR-006,NaN,No_Show,2026-04-04 17:06:00,2026-04-13 17:06:00,2026-04-15 08:06:00,60806.0,61258.0,0.25,2000,NaN,Delhi,12.874751,77.577699,fast,CARD,DL-2330XXXXXX,NaN,Navigation system malfunction reported,False,39.000000,2026-04-06 07:52:00,False,NaT,Valid
2303,RES-02304,CUST-0961,CAR-006,Luxury,Cancelled,2026-04-29 12:18:00,2026-05-02 12:18:00,2026-05-05 10:11:00,55691.0,55934.0,0.50,1500,WELCOME5,Delhi,12.856733,77.613927,fast,WALLET,DL-4160XXXXXX,Minor,Customer reported minor scratch on door,False,69.883333,2026-04-15 08:06:00,False,2026-01-31,Expired
1593,RES-01594,CUST-1448,CAR-006,unknown,No_Show,2026-05-27 16:19:00,2026-06-06 16:03:00,2026-08-06 08:51:00,66134.0,66209.0,0.30,2000,NEW10,Mumbai,12.913958,77.573615,fast,WALLET,DL-7808XXXXXX,Major,Navigation system malfunction reported,False,1456.800000,2026-05-05 10:11:00,False,2026-03-31,Expired
1305,RES-01306,CUST-0167,CAR-006,SUV,Completed,2026-09-02 04:43:00,2026-12-02 02:16:00,2026-12-02 04:43:00,56618.0,56657.0,0.30,2000,SAVE50,Delhi,12.896906,77.575727,134kmh,CASH,DL-8824XXXXXX,Minor,Customer requested early pickup,False,2.450000,2026-08-06 08:51:00,False,2026-06-30,Expired
3790,RES-03791,CUST-0336,CAR-007,unknown,No_Show,2026-02-14 01:49:00,2026-02-20 01:49:00,2026-02-21 09:49:00,63517.0,63797.0,0.50,1500,DISC20,Delhi,12.895948,77.638783,fast,CASH,DL-8317XXXXXX,Major,Vehicle returned late due to traffic,False,32.000000,NaT,False,2026-02-28,Valid
3064,RES-03065,CUST-0585,CAR-007,Hatchback,Completed,2026-03-21 02:51:00,2026-03-29 02:51:00,2026-03-29 13:51:00,46645.0,46732.0,0.75,<NA>,DISC20,NaN,12.905202,77.644689,44 km/h,UPI,DL-8349XXXXXX,NaN,NaN,False,11.000000,2026-02-21 09:49:00,False,2026-02-28,Expired
3640,RES-03641,CUST-0605,CAR-007,unknown,Cancelled,2026-03-27 08:27:00,2026-05-04 08:27:00,2026-06-04 19:27:00,50415.0,50701.0,1.00,2000,NEW10,Mumbai,12.930031,77.629405,fast,NaN,DL-6740XXXXXX,NaN,NaN,False,755.000000,2026-03-29 13:51:00,False,2026-03-31,Expired

16. Telematics GPS join and jitter smoothing.

In [32]:
# 1 check duplicates
df[['GPS_Lat','GPS_Lon']].duplicated().sum()

# 2 handle missing values
df['GPS_Lat'] = df['GPS_Lat'].interpolate()
df['GPS_Lon'] = df['GPS_Lon'].interpolate()

# 3 smooth jitter
df['GPS_Lat'] = df['GPS_Lat'].rolling(window=3, min_periods=1).mean()
df['GPS_Lon'] = df['GPS_Lon'].rolling(window=3, min_periods=1).mean()

17. Speeding/harsh events normalization from telematics.

In [33]:
# Inspect Speed Column
df["Speed"].head()

# Convert Speed Column to String
df["Speed"] = df["Speed"].astype(str)

# Remove Units (kmh and km/h)
df["Speed"] = df["Speed"].str.replace("km/h","", regex=False)
df["Speed"] = df["Speed"].str.replace("kmh","", regex=False)

# Convert "fast" to Numeric Speed

# Since "fast" means driving faster than normal, we convert it to 90 km/h.

df["Speed"] = df["Speed"].replace("fast", 90)

# Convert Entire Column to Numeric
df["Speed"] = pd.to_numeric(df["Speed"], errors="coerce")


# Create Driver Behavior Classification

def classify_speed(speed):

    if pd.isna(speed):
        return "Unknown"

    elif speed <= 80:
        return "Normal Driving"

    elif speed <= 100:
        return "Fast Driving"

    else:
        return "Speeding"


df["Driver_Behavior"] = df["Speed"].apply(classify_speed)


# Verify Result

df[["Speed","Driver_Behavior"]].head(10)

      Speed Driver_Behavior
1237  114.0        Speeding
3130  119.0        Speeding
556   117.0        Speeding
404    73.0  Normal Driving
2803  112.0        Speeding
522     NaN         Unknown
2166   62.0  Normal Driving
58     90.0    Fast Driving
2193   90.0    Fast Driving
2957    NaN         Unknown

18. PII redaction in notes and feedback.

In [34]:
df['Notes'] = df['Notes'].str.replace(r'\b\d{10}\b', '[REDACTED]', regex=True)
df['Notes'] = df['Notes'].str.replace(r'\S+@\S+', '[REDACTED]', regex=True)
df['Notes'] = df['Notes'].str.replace(r'\b[A-Z0-9]{8,}\b', '[REDACTED]', regex=True)

19. Rate plan mapping to master tariffs.

In [35]:
df['Rate'] = df['Rate'].astype(str)
df['Rate'] = df['Rate'].str.replace('[^0-9.]', '', regex=True)
df['Rate'] = pd.to_numeric(df['Rate'], errors='coerce')

20. Tax/GST computation validation.

In [36]:
#USE CASE 20: Tax/GST computation validation.

df["Rate"] = pd.to_numeric(df["Rate"], errors="coerce")
df["Total_Amount"] = (df["Rate"] * 1.18).round(2)

In [37]:
# Save cleaned dataset to CSV
df.to_csv("car_rental_cleaned_dataset.csv", index=False)
print("Cleaned dataset saved to 'car_rental_cleaned_dataset.csv'")
print(f"Final dataset shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")

Cleaned dataset saved to 'car_rental_cleaned_dataset.csv'
Final dataset shape: (3276, 29)
Columns: ['Reservation_ID', 'Customer_ID', 'Vehicle_ID', 'Vehicle_Class', 'Booking_Status', 'Booking_TS', 'Pickup_TS', 'Return_TS', 'Odo_Start', 'Odo_End', 'Fuel_Level', 'Rate', 'Promo_Code', 'City', 'GPS_Lat', 'GPS_Lon', 'Speed', 'Payment', 'Driver_License', 'Damage_Flag', 'Notes', 'Vehicle_ID_Invalid', 'Duration_Hours', 'Prev_Return', 'Overlap_Flag', 'Promo_Expiry', 'Promo_Status', 'Driver_Behavior', 'Total_Amount']