In [ ]:
# Task 1: Vehicle_ID Trimming & Canonical Case
import pandas as pd

df = pd.read_csv("../Datasets/car_rental_dirty_dataset_new1.csv")

1. Vehicle_ID trimming and canonical case.

In [ ]:
unique_vid = df['Vehicle_ID'].nunique()

# Inspect raw Vehicle_ID values
print(f"Shape: {df.shape}")
print(f"Unique Vehicle_IDs (raw): {unique_vid}")
print(sorted(df['Vehicle_ID'].dropna().unique()))
print(f"\n{df['Vehicle_ID'].value_counts().sort_index()}")

Shape: (5000, 21)
Unique Vehicle_IDs (raw): 601
[' CAR-010 ', ' CAR-014 ', ' CAR-015 ', ' CAR-027 ', ' CAR-034 ', ' CAR-045 ', ' CAR-047 ', ' CAR-063 ', ' CAR-066 ', ' CAR-070 ', ' CAR-089 ', ' CAR-091 ', ' CAR-100 ', ' CAR-101 ', ' CAR-104 ', ' CAR-112 ', ' CAR-128 ', ' CAR-133 ', ' CAR-135 ', ' CAR-137 ', ' CAR-138 ', ' CAR-148 ', ' CAR-164 ', ' CAR-169 ', ' CAR-188 ', ' CAR-190 ', ' CAR-193 ', ' CAR-195 ', ' CAR-206 ', ' CAR-213 ', ' CAR-263 ', ' CAR-275 ', ' CAR-282 ', ' CAR-286 ', ' CAR-301 ', ' CAR-303 ', ' CAR-317 ', ' CAR-333 ', ' CAR-340 ', ' CAR-343 ', ' CAR-347 ', ' CAR-369 ', ' CAR-374 ', ' CAR-379 ', ' CAR-381 ', ' CAR-385 ', ' CAR-388 ', ' CAR-396 ', ' CAR-402 ', ' CAR-430 ', ' CAR-432 ', ' CAR-435 ', ' CAR-436 ', ' CAR-440 ', ' CAR-453 ', ' CAR-471 ', ' CAR-477 ', ' CAR-480 ', ' CAR-503 ', ' CAR-504 ', ' CAR-520 ', ' CAR-533 ', ' CAR-538 ', ' CAR-564 ', ' CAR-572 ', ' CAR-583 ', ' CAR-591 ', ' CAR-594 ', ' CAR-599 ', 'CAR 005', 'CAR 011', 'CAR 020', 'CAR 030', 'CAR 031', 'CAR 043', 'CAR 056', 'CAR 060', 'CAR 074', 'CAR 081', 'CAR 086', 'CAR 103', 'CAR 117', 'CAR 119', 'CAR 127', 'CAR 131', 'CAR 136', 'CAR 141', 'CAR 145', 'CAR 161', 'CAR 166', 'CAR 171', 'CAR 203', 'CAR 212', 'CAR 216', 'CAR 219', 'CAR 223', 'CAR 236', 'CAR 242', 'CAR 255', 'CAR 261', 'CAR 290', 'CAR 296', 'CAR 304', 'CAR 305', 'CAR 349', 'CAR 351', 'CAR 356', 'CAR 359', 'CAR 362', 'CAR 368', 'CAR 389', 'CAR 398', 'CAR 400', 'CAR 421', 'CAR 422', 'CAR 425', 'CAR 433', 'CAR 444', 'CAR 449', 'CAR 454', 'CAR 462', 'CAR 484', 'CAR 485', 'CAR 498', 'CAR 508', 'CAR 511', 'CAR 515', 'CAR 522', 'CAR 535', 'CAR 551', 'CAR 552', 'CAR 553', 'CAR 559', 'CAR 563', 'CAR 565', 'CAR 575', 'CAR 588', 'CAR 598', 'CAR-001 ', 'CAR-002', 'CAR-009 ', 'CAR-012', 'CAR-018', 'CAR-023', 'CAR-024 ', 'CAR-026', 'CAR-032 ', 'CAR-035', 'CAR-036', 'CAR-048', 'CAR-049', 'CAR-052', 'CAR-057 ', 'CAR-058 ', 'CAR-061', 'CAR-062', 'CAR-065', 'CAR-069', 'CAR-071', 'CAR-073 ', 'CAR-075', 'CAR-078', 'CAR-082', 'CAR-092 ', 'CAR-093 ', 'CAR-094', 'CAR-097 ', 'CAR-099 ', 'CAR-113 ', 'CAR-114 ', 'CAR-118', 'CAR-121', 'CAR-124 ', 'CAR-125', 'CAR-130', 'CAR-132', 'CAR-142 ', 'CAR-144', 'CAR-146', 'CAR-147', 'CAR-149 ', 'CAR-155 ', 'CAR-162 ', 'CAR-172', 'CAR-182', 'CAR-183 ', 'CAR-187', 'CAR-189 ', 'CAR-196', 'CAR-202', 'CAR-204 ', 'CAR-205 ', 'CAR-215', 'CAR-218 ', 'CAR-226', 'CAR-228', 'CAR-231', 'CAR-233', 'CAR-234', 'CAR-240 ', 'CAR-241', 'CAR-246 ', 'CAR-247 ', 'CAR-256', 'CAR-269', 'CAR-271', 'CAR-274', 'CAR-277', 'CAR-280', 'CAR-281 ', 'CAR-284', 'CAR-291 ', 'CAR-294', 'CAR-297 ', 'CAR-298', 'CAR-300 ', 'CAR-310 ', 'CAR-322', 'CAR-324 ', 'CAR-327', 'CAR-328', 'CAR-329', 'CAR-331', 'CAR-332 ', 'CAR-339', 'CAR-341 ', 'CAR-345', 'CAR-348 ', 'CAR-370', 'CAR-377 ', 'CAR-394 ', 'CAR-404 ', 'CAR-405 ', 'CAR-410 ', 'CAR-415', 'CAR-416', 'CAR-418', 'CAR-426', 'CAR-427 ', 'CAR-429 ', 'CAR-434 ', 'CAR-438 ', 'CAR-442 ', 'CAR-445', 'CAR-446', 'CAR-448 ', 'CAR-450 ', 'CAR-451', 'CAR-452 ', 'CAR-460', 'CAR-464', 'CAR-468 ', 'CAR-476', 'CAR-482', 'CAR-486 ', 'CAR-494', 'CAR-502 ', 'CAR-507 ', 'CAR-512', 'CAR-517', 'CAR-521', 'CAR-523', 'CAR-524', 'CAR-527 ', 'CAR-530 ', 'CAR-534 ', 'CAR-539', 'CAR-541', 'CAR-543 ', 'CAR-544 ', 'CAR-546 ', 'CAR-550', 'CAR-558 ', 'CAR-560', 'CAR-561', 'CAR-568', 'CAR-569 ', 'CAR-576 ', 'CAR-578 ', 'CAR-580 ', 'CAR-597 ', 'CAR-600 ', 'CAR003', 'CAR013', 'CAR017', 'CAR021', 'CAR046', 'CAR083', 'CAR090', 'CAR096', 'CAR107', 'CAR111', 'CAR115', 'CAR122', 'CAR139', 'CAR143', 'CAR156', 'CAR159', 'CAR160', 'CAR163', 'CAR170', 'CAR173', 'CAR177', 'CAR180', 'CAR181', 'CAR198', 'CAR208', 'CAR214', 'CAR222', 'CAR230', 'CAR235', 'CAR245', 'CAR248', 'CAR253', 'CAR265', 'CAR268', 'CAR288', 'CAR306', 'CAR308', 'CAR314', 'CAR318', 'CAR337', 'CAR350', 'CAR358', 'CAR378', 'CAR393', 'CAR399', 'CAR407', 'CAR411', 'CAR417', 'CAR424', 'CAR447', 'CAR457', 'CAR458', 'CAR459', 'CAR461', 'CAR472', 'CAR475', 'CAR479', 'CAR493', 'CAR506', 'CAR525', 'CAR531', 'CAR536', 'CAR540', 'CAR555', 'CAR567', 'CAR577', 'CAR581', 'CAR584', 'CAR585', 'CAR586', 'CAR595', 'CAR_006', 'CAR_019', 'CAR_022', 'CAR_029', 'CAR_033', 'CAR_041', 'CAR_053', 'CAR_055', 'CAR_059', 'CAR_064', 'CAR_095', 'CAR_098', 'CAR_102', 'CAR_105', 'CAR_106', 'CAR_110', 'CAR_116', 'CAR_126', 'CAR_150', 'CAR_151', 'CAR_154', 'CAR_167', 'CAR_174', 'CAR_184', 'CAR_192', 'CAR_197', 'CAR_207', 'CAR_209', 'CAR_217', 'CAR_221', 'CAR_224', 'CAR_232', 'CAR_243', 'CAR_250', 'CAR_259', 'CAR_266', 'CAR_267', 'CAR_278', 'CAR_279', 'CAR_289', 'CAR_309', 'CAR_313', 'CAR_315', 'CAR_325', 'CAR_330', 'CAR_334', 'CAR_355', 'CAR_360', 'CAR_361', 'CAR_363', 'CAR_365', 'CAR_375', 'CAR_376', 'CAR_383', 'CAR_392', 'CAR_419', 'CAR_437', 'CAR_439', 'CAR_443', 'CAR_456', 'CAR_463', 'CAR_465', 'CAR_473', 'CAR_481', 'CAR_490', 'CAR_492', 'CAR_496', 'CAR_499', 'CAR_509', 'CAR_513', 'CAR_537', 'CAR_547', 'CAR_556', 'CAR_557', 'CAR_589', 'CAR_592', 'CAR_593', 'UNKNOWN', 'car-007', 'car-025', 'car-028', 'car-042', 'car-044', 'car-050', 'car-051', 'car-054', 'car-067', 'car-068', 'car-080', 'car-084', 'car-087', 'car-088', 'car-109', 'car-134', 'car-140', 'car-153', 'car-157', 'car-158', 'car-175', 'car-178', 'car-185', 'car-194', 'car-200', 'car-201', 'car-210', 'car-211', 'car-220', 'car-225', 'car-227', 'car-229', 'car-239', 'car-264', 'car-273', 'car-276', 'car-283', 'car-293', 'car-295', 'car-302', 'car-311', 'car-316', 'car-319', 'car-320', 'car-323', 'car-326', 'car-335', 'car-346', 'car-353', 'car-357', 'car-366', 'car-367', 'car-371', 'car-373', 'car-380', 'car-387', 'car-391', 'car-397', 'car-406', 'car-412', 'car-413', 'car-420', 'car-423', 'car-455', 'car-466', 'car-467', 'car-469', 'car-478', 'car-483', 'car-487', 'car-488', 'car-491', 'car-497', 'car-500', 'car-501', 'car-505', 'car-510', 'car-514', 'car-532', 'car-548', 'car-549', 'car-570', 'car-571', 'car-573', 'car-574', 'car-582', 'car-590', 'car-596', 'car004', 'car008', 'car016', 'car037', 'car038', 'car039', 'car040', 'car072', 'car076', 'car077', 'car079', 'car085', 'car108', 'car120', 'car123', 'car129', 'car152', 'car165', 'car168', 'car176', 'car179', 'car186', 'car191', 'car199', 'car237', 'car238', 'car244', 'car249', 'car251', 'car252', 'car254', 'car257', 'car258', 'car260', 'car262', 'car270', 'car272', 'car285', 'car287', 'car292', 'car299', 'car307', 'car312', 'car321', 'car336', 'car338', 'car342', 'car344', 'car352', 'car354', 'car364', 'car372', 'car382', 'car384', 'car386', 'car390', 'car395', 'car401', 'car403', 'car408', 'car409', 'car414', 'car428', 'car431', 'car441', 'car470', 'car474', 'car489', 'car495', 'car516', 'car518', 'car519', 'car526', 'car528', 'car529', 'car542', 'car545', 'car554', 'car562', 'car566', 'car579', 'car587']

Vehicle_ID
 CAR-010     10
 CAR-014      9
 CAR-015      8
 CAR-027     12
 CAR-034      8
             ..
car554       12
car562       13
car566       14
car579       11
car587        9
Name: count, Length: 601, dtype: int64

In [ ]:
# Clean Vehicle_ID: trim whitespace, normalize separators, canonical uppercase

# Strip leading/trailing whitespace
df['Vehicle_ID'] = df['Vehicle_ID'].str.strip()

# Normalize separators: double hyphens -> single, underscores -> hyphens
df['Vehicle_ID'] = df['Vehicle_ID'].str.replace('--', '-', regex=False)
df['Vehicle_ID'] = df['Vehicle_ID'].str.replace('_', '-', regex=False)

# Insert hyphen between letters and digits where missing (e.g., CAR08 -> CAR-08)
df['Vehicle_ID'] = df['Vehicle_ID'].str.replace(r'([A-Za-z])\s+(\d)', r'\1-\2', regex=True)
df['Vehicle_ID'] = df['Vehicle_ID'].str.replace(r'([A-Za-z])(\d)', r'\1-\2', regex=True)

# Convert to uppercase canonical form
df['Vehicle_ID'] = df['Vehicle_ID'].str.upper()

# Fix CAR-004 -> CAR-04 to match 2-digit format
df['Vehicle_ID'] = df['Vehicle_ID'].replace('CAR-004', 'CAR-04')

# Convert 'UNKNOWN' to NaN, flag invalid IDs
df['Vehicle_ID_Invalid'] = df['Vehicle_ID'].isna() | (df['Vehicle_ID'] == 'UNKNOWN')
df.loc[df['Vehicle_ID'] == 'UNKNOWN', 'Vehicle_ID'] = pd.NA

print("Cleaned Vehicle_IDs:")
print(sorted(df['Vehicle_ID'].dropna().unique()))
print(f"\n{df['Vehicle_ID'].value_counts().sort_index()}")

Cleaned Vehicle_IDs:
['CAR-001', 'CAR-002', 'CAR-003', 'CAR-005', 'CAR-006', 'CAR-007', 'CAR-008', 'CAR-009', 'CAR-010', 'CAR-011', 'CAR-012', 'CAR-013', 'CAR-014', 'CAR-015', 'CAR-016', 'CAR-017', 'CAR-018', 'CAR-019', 'CAR-020', 'CAR-021', 'CAR-022', 'CAR-023', 'CAR-024', 'CAR-025', 'CAR-026', 'CAR-027', 'CAR-028', 'CAR-029', 'CAR-030', 'CAR-031', 'CAR-032', 'CAR-033', 'CAR-034', 'CAR-035', 'CAR-036', 'CAR-037', 'CAR-038', 'CAR-039', 'CAR-04', 'CAR-040', 'CAR-041', 'CAR-042', 'CAR-043', 'CAR-044', 'CAR-045', 'CAR-046', 'CAR-047', 'CAR-048', 'CAR-049', 'CAR-050', 'CAR-051', 'CAR-052', 'CAR-053', 'CAR-054', 'CAR-055', 'CAR-056', 'CAR-057', 'CAR-058', 'CAR-059', 'CAR-060', 'CAR-061', 'CAR-062', 'CAR-063', 'CAR-064', 'CAR-065', 'CAR-066', 'CAR-067', 'CAR-068', 'CAR-069', 'CAR-070', 'CAR-071', 'CAR-072', 'CAR-073', 'CAR-074', 'CAR-075', 'CAR-076', 'CAR-077', 'CAR-078', 'CAR-079', 'CAR-080', 'CAR-081', 'CAR-082', 'CAR-083', 'CAR-084', 'CAR-085', 'CAR-086', 'CAR-087', 'CAR-088', 'CAR-089', 'CAR-090', 'CAR-091', 'CAR-092', 'CAR-093', 'CAR-094', 'CAR-095', 'CAR-096', 'CAR-097', 'CAR-098', 'CAR-099', 'CAR-100', 'CAR-101', 'CAR-102', 'CAR-103', 'CAR-104', 'CAR-105', 'CAR-106', 'CAR-107', 'CAR-108', 'CAR-109', 'CAR-110', 'CAR-111', 'CAR-112', 'CAR-113', 'CAR-114', 'CAR-115', 'CAR-116', 'CAR-117', 'CAR-118', 'CAR-119', 'CAR-120', 'CAR-121', 'CAR-122', 'CAR-123', 'CAR-124', 'CAR-125', 'CAR-126', 'CAR-127', 'CAR-128', 'CAR-129', 'CAR-130', 'CAR-131', 'CAR-132', 'CAR-133', 'CAR-134', 'CAR-135', 'CAR-136', 'CAR-137', 'CAR-138', 'CAR-139', 'CAR-140', 'CAR-141', 'CAR-142', 'CAR-143', 'CAR-144', 'CAR-145', 'CAR-146', 'CAR-147', 'CAR-148', 'CAR-149', 'CAR-150', 'CAR-151', 'CAR-152', 'CAR-153', 'CAR-154', 'CAR-155', 'CAR-156', 'CAR-157', 'CAR-158', 'CAR-159', 'CAR-160', 'CAR-161', 'CAR-162', 'CAR-163', 'CAR-164', 'CAR-165', 'CAR-166', 'CAR-167', 'CAR-168', 'CAR-169', 'CAR-170', 'CAR-171', 'CAR-172', 'CAR-173', 'CAR-174', 'CAR-175', 'CAR-176', 'CAR-177', 'CAR-178', 'CAR-179', 'CAR-180', 'CAR-181', 'CAR-182', 'CAR-183', 'CAR-184', 'CAR-185', 'CAR-186', 'CAR-187', 'CAR-188', 'CAR-189', 'CAR-190', 'CAR-191', 'CAR-192', 'CAR-193', 'CAR-194', 'CAR-195', 'CAR-196', 'CAR-197', 'CAR-198', 'CAR-199', 'CAR-200', 'CAR-201', 'CAR-202', 'CAR-203', 'CAR-204', 'CAR-205', 'CAR-206', 'CAR-207', 'CAR-208', 'CAR-209', 'CAR-210', 'CAR-211', 'CAR-212', 'CAR-213', 'CAR-214', 'CAR-215', 'CAR-216', 'CAR-217', 'CAR-218', 'CAR-219', 'CAR-220', 'CAR-221', 'CAR-222', 'CAR-223', 'CAR-224', 'CAR-225', 'CAR-226', 'CAR-227', 'CAR-228', 'CAR-229', 'CAR-230', 'CAR-231', 'CAR-232', 'CAR-233', 'CAR-234', 'CAR-235', 'CAR-236', 'CAR-237', 'CAR-238', 'CAR-239', 'CAR-240', 'CAR-241', 'CAR-242', 'CAR-243', 'CAR-244', 'CAR-245', 'CAR-246', 'CAR-247', 'CAR-248', 'CAR-249', 'CAR-250', 'CAR-251', 'CAR-252', 'CAR-253', 'CAR-254', 'CAR-255', 'CAR-256', 'CAR-257', 'CAR-258', 'CAR-259', 'CAR-260', 'CAR-261', 'CAR-262', 'CAR-263', 'CAR-264', 'CAR-265', 'CAR-266', 'CAR-267', 'CAR-268', 'CAR-269', 'CAR-270', 'CAR-271', 'CAR-272', 'CAR-273', 'CAR-274', 'CAR-275', 'CAR-276', 'CAR-277', 'CAR-278', 'CAR-279', 'CAR-280', 'CAR-281', 'CAR-282', 'CAR-283', 'CAR-284', 'CAR-285', 'CAR-286', 'CAR-287', 'CAR-288', 'CAR-289', 'CAR-290', 'CAR-291', 'CAR-292', 'CAR-293', 'CAR-294', 'CAR-295', 'CAR-296', 'CAR-297', 'CAR-298', 'CAR-299', 'CAR-300', 'CAR-301', 'CAR-302', 'CAR-303', 'CAR-304', 'CAR-305', 'CAR-306', 'CAR-307', 'CAR-308', 'CAR-309', 'CAR-310', 'CAR-311', 'CAR-312', 'CAR-313', 'CAR-314', 'CAR-315', 'CAR-316', 'CAR-317', 'CAR-318', 'CAR-319', 'CAR-320', 'CAR-321', 'CAR-322', 'CAR-323', 'CAR-324', 'CAR-325', 'CAR-326', 'CAR-327', 'CAR-328', 'CAR-329', 'CAR-330', 'CAR-331', 'CAR-332', 'CAR-333', 'CAR-334', 'CAR-335', 'CAR-336', 'CAR-337', 'CAR-338', 'CAR-339', 'CAR-340', 'CAR-341', 'CAR-342', 'CAR-343', 'CAR-344', 'CAR-345', 'CAR-346', 'CAR-347', 'CAR-348', 'CAR-349', 'CAR-350', 'CAR-351', 'CAR-352', 'CAR-353', 'CAR-354', 'CAR-355', 'CAR-356', 'CAR-357', 'CAR-358', 'CAR-359', 'CAR-360', 'CAR-361', 'CAR-362', 'CAR-363', 'CAR-364', 'CAR-365', 'CAR-366', 'CAR-367', 'CAR-368', 'CAR-369', 'CAR-370', 'CAR-371', 'CAR-372', 'CAR-373', 'CAR-374', 'CAR-375', 'CAR-376', 'CAR-377', 'CAR-378', 'CAR-379', 'CAR-380', 'CAR-381', 'CAR-382', 'CAR-383', 'CAR-384', 'CAR-385', 'CAR-386', 'CAR-387', 'CAR-388', 'CAR-389', 'CAR-390', 'CAR-391', 'CAR-392', 'CAR-393', 'CAR-394', 'CAR-395', 'CAR-396', 'CAR-397', 'CAR-398', 'CAR-399', 'CAR-400', 'CAR-401', 'CAR-402', 'CAR-403', 'CAR-404', 'CAR-405', 'CAR-406', 'CAR-407', 'CAR-408', 'CAR-409', 'CAR-410', 'CAR-411', 'CAR-412', 'CAR-413', 'CAR-414', 'CAR-415', 'CAR-416', 'CAR-417', 'CAR-418', 'CAR-419', 'CAR-420', 'CAR-421', 'CAR-422', 'CAR-423', 'CAR-424', 'CAR-425', 'CAR-426', 'CAR-427', 'CAR-428', 'CAR-429', 'CAR-430', 'CAR-431', 'CAR-432', 'CAR-433', 'CAR-434', 'CAR-435', 'CAR-436', 'CAR-437', 'CAR-438', 'CAR-439', 'CAR-440', 'CAR-441', 'CAR-442', 'CAR-443', 'CAR-444', 'CAR-445', 'CAR-446', 'CAR-447', 'CAR-448', 'CAR-449', 'CAR-450', 'CAR-451', 'CAR-452', 'CAR-453', 'CAR-454', 'CAR-455', 'CAR-456', 'CAR-457', 'CAR-458', 'CAR-459', 'CAR-460', 'CAR-461', 'CAR-462', 'CAR-463', 'CAR-464', 'CAR-465', 'CAR-466', 'CAR-467', 'CAR-468', 'CAR-469', 'CAR-470', 'CAR-471', 'CAR-472', 'CAR-473', 'CAR-474', 'CAR-475', 'CAR-476', 'CAR-477', 'CAR-478', 'CAR-479', 'CAR-480', 'CAR-481', 'CAR-482', 'CAR-483', 'CAR-484', 'CAR-485', 'CAR-486', 'CAR-487', 'CAR-488', 'CAR-489', 'CAR-490', 'CAR-491', 'CAR-492', 'CAR-493', 'CAR-494', 'CAR-495', 'CAR-496', 'CAR-497', 'CAR-498', 'CAR-499', 'CAR-500', 'CAR-501', 'CAR-502', 'CAR-503', 'CAR-504', 'CAR-505', 'CAR-506', 'CAR-507', 'CAR-508', 'CAR-509', 'CAR-510', 'CAR-511', 'CAR-512', 'CAR-513', 'CAR-514', 'CAR-515', 'CAR-516', 'CAR-517', 'CAR-518', 'CAR-519', 'CAR-520', 'CAR-521', 'CAR-522', 'CAR-523', 'CAR-524', 'CAR-525', 'CAR-526', 'CAR-527', 'CAR-528', 'CAR-529', 'CAR-530', 'CAR-531', 'CAR-532', 'CAR-533', 'CAR-534', 'CAR-535', 'CAR-536', 'CAR-537', 'CAR-538', 'CAR-539', 'CAR-540', 'CAR-541', 'CAR-542', 'CAR-543', 'CAR-544', 'CAR-545', 'CAR-546', 'CAR-547', 'CAR-548', 'CAR-549', 'CAR-550', 'CAR-551', 'CAR-552', 'CAR-553', 'CAR-554', 'CAR-555', 'CAR-556', 'CAR-557', 'CAR-558', 'CAR-559', 'CAR-560', 'CAR-561', 'CAR-562', 'CAR-563', 'CAR-564', 'CAR-565', 'CAR-566', 'CAR-567', 'CAR-568', 'CAR-569', 'CAR-570', 'CAR-571', 'CAR-572', 'CAR-573', 'CAR-574', 'CAR-575', 'CAR-576', 'CAR-577', 'CAR-578', 'CAR-579', 'CAR-580', 'CAR-581', 'CAR-582', 'CAR-583', 'CAR-584', 'CAR-585', 'CAR-586', 'CAR-587', 'CAR-588', 'CAR-589', 'CAR-590', 'CAR-591', 'CAR-592', 'CAR-593', 'CAR-594', 'CAR-595', 'CAR-596', 'CAR-597', 'CAR-598', 'CAR-599', 'CAR-600']

Vehicle_ID
CAR-001     6
CAR-002     8
CAR-003    10
CAR-005    11
CAR-006     8
           ..
CAR-596     8
CAR-597     7
CAR-598     7
CAR-599    12
CAR-600     8
Name: count, Length: 600, dtype: int64

In [ ]:
# Validate: all non-null IDs should match CAR-XX or CAR-XXX
valid_ids = df['Vehicle_ID'].dropna()
pattern_match = valid_ids.str.match(r'^CAR-\d{2,3}$')

print(f"Valid IDs: {len(valid_ids)} | Matching pattern: {pattern_match.sum()} | Non-matching: {(~pattern_match).sum()}")
if (~pattern_match).any():
    print(f"Non-matching: {valid_ids[~pattern_match].unique()}")

print(f"\nUnique Vehicle_IDs — Before: {unique_vid}, After: {df['Vehicle_ID'].nunique()}")
print(f"Invalid (NaN) Vehicle_IDs: {df['Vehicle_ID'].isna().sum()}")

Valid IDs: 4986 | Matching pattern: 4986 | Non-matching: 0

Unique Vehicle_IDs — Before: 601, After: 600
Invalid (NaN) Vehicle_IDs: 14

2. Timestamp normalization; invalid minutes fix; duration must be positive.

In [ ]:
import re
def fix_invalid_minutes(ts):
    if pd.isna(ts):
        return ts  
    match = re.search(r'(\d{1,2}):(\d{2})', str(ts))
    
    if match:
        hour = int(match.group(1))
        minute = int(match.group(2))
        
        if minute > 59:
            hour += minute // 60
            minute = minute % 60
        
        if hour > 23:
            hour = hour % 24
            
        ts = re.sub(r'\d{1,2}:\d{2}', f"{hour}:{minute:02d}", str(ts))
            
    return ts

In [ ]:
df["Pickup_TS"] = df["Pickup_TS"].apply(fix_invalid_minutes)
df["Return_TS"] = df["Return_TS"].apply(fix_invalid_minutes)
df["Booking_TS"] = df["Booking_TS"].apply(fix_invalid_minutes)
df.head(20)

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_Status,Booking_TS,Pickup_TS,Return_TS,Odo_Start,Odo_End,...,Promo_Code,City,GPS_Lat,GPS_Lon,Speed,Payment,Driver_License,Damage_Flag,Notes,Vehicle_ID_Invalid
0,RES-00001,CUST-1675,CAR-014,Hatchback,No_Show,02/13/2025 7:56,2025-02-18T7:56,18-02-2025 9:56,57815,"58,065",...,NaN,New Delhi,12.908959,77.604003,133kmh,cash,DL-2699413330,Major,Customer satisfied with ride,False
1,RES-00002,CUST-0853,CAR-230,SUV,Cancelled,08-02-2025 20:56,16-02-2025 20:56,2025-02-17 7:56,"77,762",77766km,...,NEW10,mumbai,12.946286,77.586710,55,CASH,DL-9806685378,Major,Customer requested early pickup,False
2,RES-00003,CUST-1181,CAR-001,Suzuki,Completed,2025-03-09T0:07,10-03-2025 0:07,12-03-2025 23:07,"57,856","58,238",...,DISC20,delhi,12.914102,77.627323,128 km/h,upi,DL-9542219877,Minor,Customer reported minor scratch on door,False
3,RES-00004,CUST-0182,CAR-434,Suzuki,Cancelled,04-01-2025 2:16,2025-01-11 2:16,11-01-2025 22:16,"59,967",60239km,...,SAVE50,delhi,12.873192,77.635268,25 km/h,cash,DL-4380657786,NaN,Customer requested early pickup,False
4,RES-00005,CUST-0356,CAR-121,Suzuki,No_Show,2025-05-04T4:22,2025-05-09T4:22,2025-05-10 11:22,"24,261","24,524",...,DISC20,bangalore,12.919640,77.598891,26kmh,-,DL-6429812852,Minor,AC performance slightly low,False
5,RES-00006,CUST-0061,CAR-360,Luxury,Cancelled,2025/5/27 9:18,2025-05-30T8:10,31-05-2025 9:10,"36,184","36,211",...,DISC20,chennai,12.872343,77.588487,100 km/h,card,DL-7859136756,Major,Customer reported minor scratch on door,False
6,RES-00007,CUST-0793,CAR-114,Creta,Completed,05-06-2025 14:21,08-06-2025 14:21,2025/6/9 8:02,"41,914",41881,...,WELCOME5,NaN,12.947693,77.603382,49,cash,DL-3024014652,Major,Tyre pressure alert during trip,False
7,RES-00008,CUST-0022,CAR-392,Luxury,No_Show,2025-03-28 2:32,2025/3/31 3:11,04/02/2025 5:32,"34,930",35217km,...,NEW10,Mumbai,12.927285,77.615525,fast,wallet,DL-2212993750,Major,AC performance slightly low,False
8,RES-00009,CUST-1700,CAR-505,Suzuki,No_Show,2025-04-08 12:30,2025-04-17T12:30,2025/04/17 11:30,66433,66519km,...,SAVE50,Bengaluru,12.922702,77.643999,135,netbanking,DL-1593968320,Minor,Low fuel warning observed,False
9,RES-00010,CUST-1586,CAR-448,EV,Cancelled,2025/3/15 22:18,2025/03/25 21:21,2025-03-26T5:21,"66,231",66471,...,DISC20,New Delhi,12.885247,77.596902,fast,netbanking,DL-9281443122,Major,Customer satisfied with ride,False
10,RES-00011,CUST-0312,CAR-014,Hatchback,Cancelled,2025/1/18 9:07,2025-01-24 8:53,2025-01-26T0:53,46769,"46,714",...,DISC20,Bengaluru,12.870626,77.601867,48 km/h,netbanking,DL-7283928829,Major,AC performance slightly low,False
11,RES-00012,CUST-1632,CAR-110,Creta,No_Show,11-01-2025 13:03,2025/1/18 14:16,2025-01-21T6:03,"39,028",39429km,...,SAVE50,MUM,12.864099,77.595001,117,Debit Card,DL-3241406398,NaN,Tyre pressure alert during trip,False
12,RES-00013,CUST-1659,CAR-324,Hatchback,Cancelled,2025/3/4 20:01,2025-03-06T19:40,2025/3/9 17:15,"74,779",74906,...,NEW10,Mumbai,12.905973,77.620244,fast,upi,DL-6141484397,NaN,Tyre pressure alert during trip,False
13,RES-00014,CUST-0153,CAR-552,Sedan,Completed,2025/06/12 13:52,2025-06-18 13:52,2025-06-19T22:52,59744 km,59864km,...,NaN,Chennai,12.908284,77.576681,125,Credit Card,DL-6054097310,NaN,Interior cleaning required,False
14,RES-00015,CUST-0236,CAR-376,Creta,No_Show,2025/4/6 9:03,2025-04-14 8:45,14-04-2025 13:45,57727 km,57744km,...,NEW10,New Delhi,12.873896,77.589052,73,NaN,DL-5317398731,NaN,AC performance slightly low,False
15,RES-00016,CUST-1618,CAR-424,Toyota,No_Show,04/18/2025 8:13,2025-04-24T8:13,04/25/2025 22:13,"24,556",24567km,...,DISC20,New Delhi,12.922112,77.629138,131kmh,cash,DL-7729892640,Minor,Navigation system malfunction reported,False
16,RES-00017,CUST-1438,CAR-569,Creta,Completed,30-04-2025 7:14,2025/5/7 8:15,08-05-2025 4:14,32923 km,"33,087",...,SAVE50,mumbai,12.888885,77.578787,76kmh,Credit Card,DL-2789946880,Minor,Interior cleaning required,False
17,RES-00018,CUST-1016,CAR-237,SUV,Completed,20-05-2025 8:56,2025-05-30T8:56,2025/5/30 5:02,"11,153",11183,...,NEW10,NaN,12.866332,77.572247,123 km/h,wallet,DL-7299397205,NaN,Customer reported minor scratch on door,False
18,RES-00019,CUST-1792,CAR-569,Creta,Cancelled,31-12-2024 9:06,2025/1/6 10:19,2025-01-09 1:06,29538,"29,762",...,SAVE50,delhi,12.855743,77.646484,121kmh,netbanking,DL-2769240560,Minor,Customer reported minor scratch on door,False
19,RES-00020,CUST-0662,CAR-042,SUV,Completed,2024-12-23 8:45,2025-01-01 8:45,2025-01-03 15:45,75137 km,"75,100",...,SAVE50,bangalore,12.898705,77.565579,76kmh,CARD,DL-3306432231,NaN,Car returned in good condition,False

In [ ]:
df["Pickup_TS"] = df["Pickup_TS"].str.replace("/", "-", regex=False).str.replace("T", " ", regex=False)
df["Return_TS"] = df["Return_TS"].str.replace("/", "-", regex=False).str.replace("T", " ", regex=False)
df["Booking_TS"] = df["Booking_TS"].str.replace("/", "-", regex=False).str.replace("T", " ", regex=False)

In [ ]:
df["Pickup_TS"] = pd.to_datetime(df["Pickup_TS"], format='mixed', dayfirst=True)
df["Return_TS"] = pd.to_datetime(df["Return_TS"], format='mixed', dayfirst=True)
df["Booking_TS"] = pd.to_datetime(df["Booking_TS"], format='mixed', dayfirst=True)

In [ ]:
df.head(20)

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_Status,Booking_TS,Pickup_TS,Return_TS,Odo_Start,Odo_End,...,Promo_Code,City,GPS_Lat,GPS_Lon,Speed,Payment,Driver_License,Damage_Flag,Notes,Vehicle_ID_Invalid
0,RES-00001,CUST-1675,CAR-014,Hatchback,No_Show,2025-02-13 07:56:00,2025-02-18 07:56:00,2025-02-18 09:56:00,57815,"58,065",...,NaN,New Delhi,12.908959,77.604003,133kmh,cash,DL-2699413330,Major,Customer satisfied with ride,False
1,RES-00002,CUST-0853,CAR-230,SUV,Cancelled,2025-02-08 20:56:00,2025-02-16 20:56:00,2025-02-17 07:56:00,"77,762",77766km,...,NEW10,mumbai,12.946286,77.586710,55,CASH,DL-9806685378,Major,Customer requested early pickup,False
2,RES-00003,CUST-1181,CAR-001,Suzuki,Completed,2025-09-03 00:07:00,2025-03-10 00:07:00,2025-03-12 23:07:00,"57,856","58,238",...,DISC20,delhi,12.914102,77.627323,128 km/h,upi,DL-9542219877,Minor,Customer reported minor scratch on door,False
3,RES-00004,CUST-0182,CAR-434,Suzuki,Cancelled,2025-01-04 02:16:00,2025-11-01 02:16:00,2025-01-11 22:16:00,"59,967",60239km,...,SAVE50,delhi,12.873192,77.635268,25 km/h,cash,DL-4380657786,NaN,Customer requested early pickup,False
4,RES-00005,CUST-0356,CAR-121,Suzuki,No_Show,2025-04-05 04:22:00,2025-09-05 04:22:00,2025-10-05 11:22:00,"24,261","24,524",...,DISC20,bangalore,12.919640,77.598891,26kmh,-,DL-6429812852,Minor,AC performance slightly low,False
5,RES-00006,CUST-0061,CAR-360,Luxury,Cancelled,2025-05-27 09:18:00,2025-05-30 08:10:00,2025-05-31 09:10:00,"36,184","36,211",...,DISC20,chennai,12.872343,77.588487,100 km/h,card,DL-7859136756,Major,Customer reported minor scratch on door,False
6,RES-00007,CUST-0793,CAR-114,Creta,Completed,2025-06-05 14:21:00,2025-06-08 14:21:00,2025-09-06 08:02:00,"41,914",41881,...,WELCOME5,NaN,12.947693,77.603382,49,cash,DL-3024014652,Major,Tyre pressure alert during trip,False
7,RES-00008,CUST-0022,CAR-392,Luxury,No_Show,2025-03-28 02:32:00,2025-03-31 03:11:00,2025-02-04 05:32:00,"34,930",35217km,...,NEW10,Mumbai,12.927285,77.615525,fast,wallet,DL-2212993750,Major,AC performance slightly low,False
8,RES-00009,CUST-1700,CAR-505,Suzuki,No_Show,2025-08-04 12:30:00,2025-04-17 12:30:00,2025-04-17 11:30:00,66433,66519km,...,SAVE50,Bengaluru,12.922702,77.643999,135,netbanking,DL-1593968320,Minor,Low fuel warning observed,False
9,RES-00010,CUST-1586,CAR-448,EV,Cancelled,2025-03-15 22:18:00,2025-03-25 21:21:00,2025-03-26 05:21:00,"66,231",66471,...,DISC20,New Delhi,12.885247,77.596902,fast,netbanking,DL-9281443122,Major,Customer satisfied with ride,False
10,RES-00011,CUST-0312,CAR-014,Hatchback,Cancelled,2025-01-18 09:07:00,2025-01-24 08:53:00,2025-01-26 00:53:00,46769,"46,714",...,DISC20,Bengaluru,12.870626,77.601867,48 km/h,netbanking,DL-7283928829,Major,AC performance slightly low,False
11,RES-00012,CUST-1632,CAR-110,Creta,No_Show,2025-01-11 13:03:00,2025-01-18 14:16:00,2025-01-21 06:03:00,"39,028",39429km,...,SAVE50,MUM,12.864099,77.595001,117,Debit Card,DL-3241406398,NaN,Tyre pressure alert during trip,False
12,RES-00013,CUST-1659,CAR-324,Hatchback,Cancelled,2025-04-03 20:01:00,2025-06-03 19:40:00,2025-09-03 17:15:00,"74,779",74906,...,NEW10,Mumbai,12.905973,77.620244,fast,upi,DL-6141484397,NaN,Tyre pressure alert during trip,False
13,RES-00014,CUST-0153,CAR-552,Sedan,Completed,2025-12-06 13:52:00,2025-06-18 13:52:00,2025-06-19 22:52:00,59744 km,59864km,...,NaN,Chennai,12.908284,77.576681,125,Credit Card,DL-6054097310,NaN,Interior cleaning required,False
14,RES-00015,CUST-0236,CAR-376,Creta,No_Show,2025-06-04 09:03:00,2025-04-14 08:45:00,2025-04-14 13:45:00,57727 km,57744km,...,NEW10,New Delhi,12.873896,77.589052,73,NaN,DL-5317398731,NaN,AC performance slightly low,False
15,RES-00016,CUST-1618,CAR-424,Toyota,No_Show,2025-04-18 08:13:00,2025-04-24 08:13:00,2025-04-25 22:13:00,"24,556",24567km,...,DISC20,New Delhi,12.922112,77.629138,131kmh,cash,DL-7729892640,Minor,Navigation system malfunction reported,False
16,RES-00017,CUST-1438,CAR-569,Creta,Completed,2025-04-30 07:14:00,2025-07-05 08:15:00,2025-05-08 04:14:00,32923 km,"33,087",...,SAVE50,mumbai,12.888885,77.578787,76kmh,Credit Card,DL-2789946880,Minor,Interior cleaning required,False
17,RES-00018,CUST-1016,CAR-237,SUV,Completed,2025-05-20 08:56:00,2025-05-30 08:56:00,2025-05-30 05:02:00,"11,153",11183,...,NEW10,NaN,12.866332,77.572247,123 km/h,wallet,DL-7299397205,NaN,Customer reported minor scratch on door,False
18,RES-00019,CUST-1792,CAR-569,Creta,Cancelled,2024-12-31 09:06:00,2025-06-01 10:19:00,2025-09-01 01:06:00,29538,"29,762",...,SAVE50,delhi,12.855743,77.646484,121kmh,netbanking,DL-2769240560,Minor,Customer reported minor scratch on door,False
19,RES-00020,CUST-0662,CAR-042,SUV,Completed,2024-12-23 08:45:00,2025-01-01 08:45:00,2025-03-01 15:45:00,75137 km,"75,100",...,SAVE50,bangalore,12.898705,77.565579,76kmh,CARD,DL-3306432231,NaN,Car returned in good condition,False

3. Odometer numeric extraction and unit unification (km)

In [ ]:
def clean_odometer(value):

    if pd.isna(value):
        return pd.NA

    # convert to string
    value = str(value)

    # remove commas (12,519 → 12519)
    value = value.replace(",", "")

    # remove non-numeric characters (remove km etc.)
    value = re.sub(r'[^0-9.]', '', value)

    if value == "":
        return pd.NA

    return float(value)
# Apply function to both odometer columns
df['Odo_Start'] = df['Odo_Start'].apply(clean_odometer)
df['Odo_End'] = df['Odo_End'].apply(clean_odometer)

print(df[['Odo_Start','Odo_End']].head(10))

   Odo_Start  Odo_End
0    57815.0  58065.0
1    77762.0  77766.0
2    57856.0  58238.0
3    59967.0  60239.0
4    24261.0  24524.0
5    36184.0  36211.0
6    41914.0  41881.0
7    34930.0  35217.0
8    66433.0  66519.0
9    66231.0  66471.0

4. Fuel level normalization (50%→0.5)

In [ ]:
# Remove % symbol
df["Fuel_Level"] = df["Fuel_Level"].astype(str).str.replace("%", "")

# Convert column to numeric
df["Fuel_Level"] = pd.to_numeric(df["Fuel_Level"], errors="coerce")

# Convert percentage values to fraction
df.loc[df["Fuel_Level"] > 1, "Fuel_Level"] = df["Fuel_Level"] / 100

df['Fuel_Level'].unique()

array([0.1 ,  nan, 0.3 , 0.5 , 0.75, 1.  , 0.25])

5. Rate parsing to numeric daily rate; currency normalization.

In [ ]:
usd_to_inr = 92
eur_to_inr = 106

def clean_rate(val):

    if pd.isna(val):
        return pd.NA

    val = str(val).replace(",", "").strip()

    # USD values
    if "USD" in val or "$" in val:
        num = re.findall(r'\d+', val)
        if num:
            return int(num[0]) * usd_to_inr

    # EURO values
    if "EUR" in val or "€" in val:
        num = re.findall(r'\d+', val)
        if num:
            return int(num[0]) * eur_to_inr

    # INR values
    num = re.findall(r'\d+', val)
    if num:
        return int(num[0])

    return pd.NA


df["Rate"] = df["Rate"].apply(clean_rate)

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
df.head(20)

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_Status,Booking_TS,Pickup_TS,Return_TS,Odo_Start,Odo_End,Fuel_Level,Rate,Promo_Code,City,GPS_Lat,GPS_Lon,Speed,Payment,Driver_License,Damage_Flag,Notes,Vehicle_ID_Invalid
0,RES-00001,CUST-1675,CAR-014,Hatchback,No_Show,2025-02-13 07:56:00,2025-02-18 07:56:00,2025-02-18 09:56:00,57815.0,58065.0,0.10,1840,NaN,New Delhi,12.908959,77.604003,133kmh,cash,DL-2699413330,Major,Customer satisfied with ride,False
1,RES-00002,CUST-0853,CAR-230,SUV,Cancelled,2025-02-08 20:56:00,2025-02-16 20:56:00,2025-02-17 07:56:00,77762.0,77766.0,NaN,2000,NEW10,mumbai,12.946286,77.586710,55,CASH,DL-9806685378,Major,Customer requested early pickup,False
2,RES-00003,CUST-1181,CAR-001,Suzuki,Completed,2025-09-03 00:07:00,2025-03-10 00:07:00,2025-03-12 23:07:00,57856.0,58238.0,0.30,2000,DISC20,delhi,12.914102,77.627323,128 km/h,upi,DL-9542219877,Minor,Customer reported minor scratch on door,False
3,RES-00004,CUST-0182,CAR-434,Suzuki,Cancelled,2025-01-04 02:16:00,2025-11-01 02:16:00,2025-01-11 22:16:00,59967.0,60239.0,0.50,1500,SAVE50,delhi,12.873192,77.635268,25 km/h,cash,DL-4380657786,NaN,Customer requested early pickup,False
4,RES-00005,CUST-0356,CAR-121,Suzuki,No_Show,2025-04-05 04:22:00,2025-09-05 04:22:00,2025-10-05 11:22:00,24261.0,24524.0,0.75,2300,DISC20,bangalore,12.919640,77.598891,26kmh,-,DL-6429812852,Minor,AC performance slightly low,False
5,RES-00006,CUST-0061,CAR-360,Luxury,Cancelled,2025-05-27 09:18:00,2025-05-30 08:10:00,2025-05-31 09:10:00,36184.0,36211.0,0.75,2500,DISC20,chennai,12.872343,77.588487,100 km/h,card,DL-7859136756,Major,Customer reported minor scratch on door,False
6,RES-00007,CUST-0793,CAR-114,Creta,Completed,2025-06-05 14:21:00,2025-06-08 14:21:00,2025-09-06 08:02:00,41914.0,41881.0,0.30,2000,WELCOME5,NaN,12.947693,77.603382,49,cash,DL-3024014652,Major,Tyre pressure alert during trip,False
7,RES-00008,CUST-0022,CAR-392,Luxury,No_Show,2025-03-28 02:32:00,2025-03-31 03:11:00,2025-02-04 05:32:00,34930.0,35217.0,0.75,1800,NEW10,Mumbai,12.927285,77.615525,fast,wallet,DL-2212993750,Major,AC performance slightly low,False
8,RES-00009,CUST-1700,CAR-505,Suzuki,No_Show,2025-08-04 12:30:00,2025-04-17 12:30:00,2025-04-17 11:30:00,66433.0,66519.0,1.00,1800,SAVE50,Bengaluru,12.922702,77.643999,135,netbanking,DL-1593968320,Minor,Low fuel warning observed,False
9,RES-00010,CUST-1586,CAR-448,EV,Cancelled,2025-03-15 22:18:00,2025-03-25 21:21:00,2025-03-26 05:21:00,66231.0,66471.0,0.25,<NA>,DISC20,New Delhi,12.885247,77.596902,fast,netbanking,DL-9281443122,Major,Customer satisfied with ride,False
10,RES-00011,CUST-0312,CAR-014,Hatchback,Cancelled,2025-01-18 09:07:00,2025-01-24 08:53:00,2025-01-26 00:53:00,46769.0,46714.0,1.00,2000,DISC20,Bengaluru,12.870626,77.601867,48 km/h,netbanking,DL-7283928829,Major,AC performance slightly low,False
11,RES-00012,CUST-1632,CAR-110,Creta,No_Show,2025-01-11 13:03:00,2025-01-18 14:16:00,2025-01-21 06:03:00,39028.0,39429.0,1.00,2500,SAVE50,MUM,12.864099,77.595001,117,Debit Card,DL-3241406398,NaN,Tyre pressure alert during trip,False
12,RES-00013,CUST-1659,CAR-324,Hatchback,Cancelled,2025-04-03 20:01:00,2025-06-03 19:40:00,2025-09-03 17:15:00,74779.0,74906.0,1.00,1500,NEW10,Mumbai,12.905973,77.620244,fast,upi,DL-6141484397,NaN,Tyre pressure alert during trip,False
13,RES-00014,CUST-0153,CAR-552,Sedan,Completed,2025-12-06 13:52:00,2025-06-18 13:52:00,2025-06-19 22:52:00,59744.0,59864.0,0.25,2500,NaN,Chennai,12.908284,77.576681,125,Credit Card,DL-6054097310,NaN,Interior cleaning required,False
14,RES-00015,CUST-0236,CAR-376,Creta,No_Show,2025-06-04 09:03:00,2025-04-14 08:45:00,2025-04-14 13:45:00,57727.0,57744.0,0.10,<NA>,NEW10,New Delhi,12.873896,77.589052,73,NaN,DL-5317398731,NaN,AC performance slightly low,False
15,RES-00016,CUST-1618,CAR-424,Toyota,No_Show,2025-04-18 08:13:00,2025-04-24 08:13:00,2025-04-25 22:13:00,24556.0,24567.0,NaN,2000,DISC20,New Delhi,12.922112,77.629138,131kmh,cash,DL-7729892640,Minor,Navigation system malfunction reported,False
16,RES-00017,CUST-1438,CAR-569,Creta,Completed,2025-04-30 07:14:00,2025-07-05 08:15:00,2025-05-08 04:14:00,32923.0,33087.0,1.00,2300,SAVE50,mumbai,12.888885,77.578787,76kmh,Credit Card,DL-2789946880,Minor,Interior cleaning required,False
17,RES-00018,CUST-1016,CAR-237,SUV,Completed,2025-05-20 08:56:00,2025-05-30 08:56:00,2025-05-30 05:02:00,11153.0,11183.0,0.50,1800,NEW10,NaN,12.866332,77.572247,123 km/h,wallet,DL-7299397205,NaN,Customer reported minor scratch on door,False
18,RES-00019,CUST-1792,CAR-569,Creta,Cancelled,2024-12-31 09:06:00,2025-06-01 10:19:00,2025-09-01 01:06:00,29538.0,29762.0,0.75,2000,SAVE50,delhi,12.855743,77.646484,121kmh,netbanking,DL-2769240560,Minor,Customer reported minor scratch on door,False
19,RES-00020,CUST-0662,CAR-042,SUV,Completed,2024-12-23 08:45:00,2025-01-01 08:45:00,2025-03-01 15:45:00,75137.0,75100.0,0.50,<NA>,SAVE50,bangalore,12.898705,77.565579,76kmh,CARD,DL-3306432231,NaN,Car returned in good condition,False

6. City normalization to canonical names.

In [ ]:
# Check unique city values before cleaning
print("Cities BEFORE cleaning:")
print(df["City"].unique())

# Step 1: Remove spaces
df["City"] = df["City"].str.strip()

# Step 2: Convert everything to lowercase
df["City"] = df["City"].str.lower()

# Step 3: Replace unknown and missing values with NA
df["City"] = df["City"].replace("unknown", pd.NA)

# Step 4: Map inconsistent names to standard names
city_mapping = {
    "blr": "bengaluru",
    "bangalore": "bengaluru",
    "bengaluru": "bengaluru",

    "mum": "mumbai",
    "bombay": "mumbai",
    "mumbai": "mumbai",

    "del": "delhi",
    "delhi": "delhi",
    "new delhi": "delhi",

    "chn": "chennai",
    "chennai": "chennai",

}

df["City"] = df["City"].replace(city_mapping)

# Step 5: Convert to title case
df["City"] = df["City"].str.title()

df["City"].value_counts()

# Check unique city values after cleaning
print("Cities AFTER cleaning:")
print(df["City"].unique())

Cities BEFORE cleaning:
<StringArray>
['New Delhi',    'mumbai',     'delhi', 'bangalore',   'chennai',         nan,
    'Mumbai', 'Bengaluru',       'MUM',   'Chennai',       'BLR',     'Delhi',
       'CHN',   'unknown',    'Bombay',       'blr',     'DELHI']
Length: 17, dtype: str
Cities AFTER cleaning:
<StringArray>
['Delhi', 'Mumbai', 'Bengaluru', 'Chennai', nan]
Length: 5, dtype: str

7. Duplicate reservation dedup (same ID).

In [ ]:
print(f"Duplicate Reservation_IDs: {df['Reservation_ID'].duplicated().sum()}")
df = df.drop_duplicates(subset='Reservation_ID', keep='first')
print(f"Shape after dedup: {df.shape}")

Duplicate Reservation_IDs: 473
Shape after dedup: (4527, 22)

8. Return before pickup rule validation.

In [ ]:
swap_mask = df["Return_TS"] < df["Pickup_TS"]

df.loc[swap_mask, ["Pickup_TS","Return_TS"]] = \
df.loc[swap_mask, ["Return_TS","Pickup_TS"]].values

In [ ]:
df["Duration_Hours"] = (df["Return_TS"] - df["Pickup_TS"]).dt.total_seconds() / 3600

In [ ]:
invalid_duration = df[df["Duration_Hours"] < 0]

In [ ]:
equal_mask = df["Return_TS"] == df["Pickup_TS"]

In [ ]:
df.loc[equal_mask, ["Pickup_TS", "Return_TS"]] = pd.NaT

In [ ]:
print(invalid_duration)

Empty DataFrame
Columns: [Reservation_ID, Customer_ID, Vehicle_ID, Vehicle_Class, Booking_Status, Booking_TS, Pickup_TS, Return_TS, Odo_Start, Odo_End, Fuel_Level, Rate, Promo_Code, City, GPS_Lat, GPS_Lon, Speed, Payment, Driver_License, Damage_Flag, Notes, Vehicle_ID_Invalid, Duration_Hours]
Index: []

In [ ]:
df.head(20)

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_Status,Booking_TS,Pickup_TS,Return_TS,Odo_Start,Odo_End,Fuel_Level,Rate,Promo_Code,City,GPS_Lat,GPS_Lon,Speed,Payment,Driver_License,Damage_Flag,Notes,Vehicle_ID_Invalid,Duration_Hours
0,RES-00001,CUST-1675,CAR-014,Hatchback,No_Show,2025-02-13 07:56:00,2025-02-18 07:56:00,2025-02-18 09:56:00,57815.0,58065.0,0.10,1840,NaN,Delhi,12.908959,77.604003,133kmh,cash,DL-2699413330,Major,Customer satisfied with ride,False,2.000000
1,RES-00002,CUST-0853,CAR-230,SUV,Cancelled,2025-02-08 20:56:00,2025-02-16 20:56:00,2025-02-17 07:56:00,77762.0,77766.0,NaN,2000,NEW10,Mumbai,12.946286,77.586710,55,CASH,DL-9806685378,Major,Customer requested early pickup,False,11.000000
2,RES-00003,CUST-1181,CAR-001,Suzuki,Completed,2025-09-03 00:07:00,2025-03-10 00:07:00,2025-03-12 23:07:00,57856.0,58238.0,0.30,2000,DISC20,Delhi,12.914102,77.627323,128 km/h,upi,DL-9542219877,Minor,Customer reported minor scratch on door,False,71.000000
3,RES-00004,CUST-0182,CAR-434,Suzuki,Cancelled,2025-01-04 02:16:00,2025-01-11 22:16:00,2025-11-01 02:16:00,59967.0,60239.0,0.50,1500,SAVE50,Delhi,12.873192,77.635268,25 km/h,cash,DL-4380657786,NaN,Customer requested early pickup,False,7036.000000
4,RES-00005,CUST-0356,CAR-121,Suzuki,No_Show,2025-04-05 04:22:00,2025-09-05 04:22:00,2025-10-05 11:22:00,24261.0,24524.0,0.75,2300,DISC20,Bengaluru,12.919640,77.598891,26kmh,-,DL-6429812852,Minor,AC performance slightly low,False,727.000000
5,RES-00006,CUST-0061,CAR-360,Luxury,Cancelled,2025-05-27 09:18:00,2025-05-30 08:10:00,2025-05-31 09:10:00,36184.0,36211.0,0.75,2500,DISC20,Chennai,12.872343,77.588487,100 km/h,card,DL-7859136756,Major,Customer reported minor scratch on door,False,25.000000
6,RES-00007,CUST-0793,CAR-114,Creta,Completed,2025-06-05 14:21:00,2025-06-08 14:21:00,2025-09-06 08:02:00,41914.0,41881.0,0.30,2000,WELCOME5,NaN,12.947693,77.603382,49,cash,DL-3024014652,Major,Tyre pressure alert during trip,False,2153.683333
7,RES-00008,CUST-0022,CAR-392,Luxury,No_Show,2025-03-28 02:32:00,2025-02-04 05:32:00,2025-03-31 03:11:00,34930.0,35217.0,0.75,1800,NEW10,Mumbai,12.927285,77.615525,fast,wallet,DL-2212993750,Major,AC performance slightly low,False,1317.650000
8,RES-00009,CUST-1700,CAR-505,Suzuki,No_Show,2025-08-04 12:30:00,2025-04-17 11:30:00,2025-04-17 12:30:00,66433.0,66519.0,1.00,1800,SAVE50,Bengaluru,12.922702,77.643999,135,netbanking,DL-1593968320,Minor,Low fuel warning observed,False,1.000000
9,RES-00010,CUST-1586,CAR-448,EV,Cancelled,2025-03-15 22:18:00,2025-03-25 21:21:00,2025-03-26 05:21:00,66231.0,66471.0,0.25,<NA>,DISC20,Delhi,12.885247,77.596902,fast,netbanking,DL-9281443122,Major,Customer satisfied with ride,False,8.000000
10,RES-00011,CUST-0312,CAR-014,Hatchback,Cancelled,2025-01-18 09:07:00,2025-01-24 08:53:00,2025-01-26 00:53:00,46769.0,46714.0,1.00,2000,DISC20,Bengaluru,12.870626,77.601867,48 km/h,netbanking,DL-7283928829,Major,AC performance slightly low,False,40.000000
11,RES-00012,CUST-1632,CAR-110,Creta,No_Show,2025-01-11 13:03:00,2025-01-18 14:16:00,2025-01-21 06:03:00,39028.0,39429.0,1.00,2500,SAVE50,Mumbai,12.864099,77.595001,117,Debit Card,DL-3241406398,NaN,Tyre pressure alert during trip,False,63.783333
12,RES-00013,CUST-1659,CAR-324,Hatchback,Cancelled,2025-04-03 20:01:00,2025-06-03 19:40:00,2025-09-03 17:15:00,74779.0,74906.0,1.00,1500,NEW10,Mumbai,12.905973,77.620244,fast,upi,DL-6141484397,NaN,Tyre pressure alert during trip,False,2205.583333
13,RES-00014,CUST-0153,CAR-552,Sedan,Completed,2025-12-06 13:52:00,2025-06-18 13:52:00,2025-06-19 22:52:00,59744.0,59864.0,0.25,2500,NaN,Chennai,12.908284,77.576681,125,Credit Card,DL-6054097310,NaN,Interior cleaning required,False,33.000000
14,RES-00015,CUST-0236,CAR-376,Creta,No_Show,2025-06-04 09:03:00,2025-04-14 08:45:00,2025-04-14 13:45:00,57727.0,57744.0,0.10,<NA>,NEW10,Delhi,12.873896,77.589052,73,NaN,DL-5317398731,NaN,AC performance slightly low,False,5.000000
15,RES-00016,CUST-1618,CAR-424,Toyota,No_Show,2025-04-18 08:13:00,2025-04-24 08:13:00,2025-04-25 22:13:00,24556.0,24567.0,NaN,2000,DISC20,Delhi,12.922112,77.629138,131kmh,cash,DL-7729892640,Minor,Navigation system malfunction reported,False,38.000000
16,RES-00017,CUST-1438,CAR-569,Creta,Completed,2025-04-30 07:14:00,2025-05-08 04:14:00,2025-07-05 08:15:00,32923.0,33087.0,1.00,2300,SAVE50,Mumbai,12.888885,77.578787,76kmh,Credit Card,DL-2789946880,Minor,Interior cleaning required,False,1396.016667
17,RES-00018,CUST-1016,CAR-237,SUV,Completed,2025-05-20 08:56:00,2025-05-30 05:02:00,2025-05-30 08:56:00,11153.0,11183.0,0.50,1800,NEW10,NaN,12.866332,77.572247,123 km/h,wallet,DL-7299397205,NaN,Customer reported minor scratch on door,False,3.900000
18,RES-00019,CUST-1792,CAR-569,Creta,Cancelled,2024-12-31 09:06:00,2025-06-01 10:19:00,2025-09-01 01:06:00,29538.0,29762.0,0.75,2000,SAVE50,Delhi,12.855743,77.646484,121kmh,netbanking,DL-2769240560,Minor,Customer reported minor scratch on door,False,2198.783333
19,RES-00020,CUST-0662,CAR-042,SUV,Completed,2024-12-23 08:45:00,2025-01-01 08:45:00,2025-03-01 15:45:00,75137.0,75100.0,0.50,<NA>,SAVE50,Bengaluru,12.898705,77.565579,76kmh,CARD,DL-3306432231,NaN,Car returned in good condition,False,1423.000000

9. Payment method standardization (UPI/CARD/CASH/WALLET).

In [ ]:
df["Payment"] = df["Payment"].astype(str).str.lower().str.strip()

payment_dict = {
    "upi": "UPI",
    
    "credit card": "CARD",
    "debit card": "CARD",
    "card": "CARD",
    "netbanking": "CARD",
    
    "cash": "CASH",
    
    "wallet": "WALLET",
    
    "-": pd.NA,
    "nan": pd.NA
}

df["Payment"] = df["Payment"].replace(payment_dict)
print(df["Payment"].unique())

<StringArray>
['CASH', 'UPI', nan, 'CARD', 'WALLET']
Length: 5, dtype: str

10. Mileage sanity check (End ≥ Start)

In [ ]:
mileage_check = df[['Reservation_ID','Odo_Start','Odo_End']].copy()

# Swap Odo_Start and Odo_End where End < Start (likely data entry error)
odo_swap_mask = df['Odo_End'] < df['Odo_Start']
df.loc[odo_swap_mask, ['Odo_Start', 'Odo_End']] = df.loc[odo_swap_mask, ['Odo_End', 'Odo_Start']].values
print(f"Swapped Odo_Start/Odo_End for {odo_swap_mask.sum()} rows")

# Verify no invalid mileages remain
mileage_check = df[['Reservation_ID','Odo_Start','Odo_End']].copy()
mileage_check['Mileage_Valid'] = mileage_check['Odo_End'] >= mileage_check['Odo_Start']
print(f"Invalid mileages remaining: {(~mileage_check['Mileage_Valid']).sum()}")
mileage_check.head(10)

Swapped Odo_Start/Odo_End for 745 rows
Invalid mileages remaining: 0

  Reservation_ID  Odo_Start  Odo_End  Mileage_Valid
0      RES-00001    57815.0  58065.0           True
1      RES-00002    77762.0  77766.0           True
2      RES-00003    57856.0  58238.0           True
3      RES-00004    59967.0  60239.0           True
4      RES-00005    24261.0  24524.0           True
5      RES-00006    36184.0  36211.0           True
6      RES-00007    41881.0  41914.0           True
7      RES-00008    34930.0  35217.0           True
8      RES-00009    66433.0  66519.0           True
9      RES-00010    66231.0  66471.0           True

11. Refueling event detection vs fuel change and distance.

In [ ]:
# Step 1: Normalize Fuel_Level (re-normalize in case of any remaining % values)
df["Fuel_Level"] = df["Fuel_Level"].astype(str).str.replace("%", "", regex=False)
df["Fuel_Level"] = pd.to_numeric(df["Fuel_Level"], errors="coerce")

# Convert percentage values to fraction
df.loc[df["Fuel_Level"] > 1, "Fuel_Level"] = df["Fuel_Level"] / 100

# Step 2: Prepare validity mask and distance driven directly on main dataframe
valid_odo_mask = df["Odo_End"] >= df["Odo_Start"]
df["Distance_Driven"] = pd.NA
df.loc[valid_odo_mask, "Distance_Driven"] = (
    df.loc[valid_odo_mask, "Odo_End"] - df.loc[valid_odo_mask, "Odo_Start"]
)

# Step 3: Detect refuel events directly on main dataframe
sorted_idx = df.sort_values(["Vehicle_ID", "Odo_Start"]).index
fuel_diff = df.loc[sorted_idx].groupby("Vehicle_ID")["Fuel_Level"].diff()
refuel_flag = (fuel_diff > 0).map({True: "Refueled", False: "No Refuel"})

df["Refuel_Event"] = pd.NA
df.loc[refuel_flag.index, "Refuel_Event"] = refuel_flag
df.loc[~valid_odo_mask, "Refuel_Event"] = pd.NA

# Step 4: Display
df.head(10)
df['Refuel_Event'].unique()

array(['No Refuel', 'Refueled'], dtype=object)

12. Vehicle availability overlap checks.

In [ ]:
df = df.sort_values(['Vehicle_ID','Pickup_TS'])

df['Prev_Return'] = df.groupby('Vehicle_ID')['Return_TS'].shift(1)

df['Overlap_Flag'] = df['Pickup_TS'] < df['Prev_Return']

df['Overlap_Flag'].value_counts()

Overlap_Flag
False    3235
True     1292
Name: count, dtype: int64

13. Damage / Incident Log Linkage to Reservation

In [ ]:
#inspect
df[['Reservation_ID','Vehicle_ID','Customer_ID','Damage_Flag','Notes']].head()

#Extract rows where damage was reported
damage_logs = df[
    df['Damage_Flag'].notna() &
    (df['Damage_Flag'] != 'None')
]


#Create a separate incident log dataset
incident_log = damage_logs[[
    'Reservation_ID',
    'Vehicle_ID',
    'Customer_ID',
    'Damage_Flag',
    'Notes'
]].copy()


#Check for records where damage is flagged but notes are missing
missing_notes = incident_log[
    incident_log['Notes'].isna() |
    (incident_log['Notes'].str.strip() == "")
]


print("Damage incidents missing description:", len(missing_notes))


#Detect possible damage mentioned in notes but flag is 'None'
possible_damage = df[
    (df['Damage_Flag'] == 'None') &
    (df['Notes'].str.contains('damage|scratch|dent|crack', case=False, na=False))
]


print("Possible misclassified incidents:", len(possible_damage))


#Display the final incident log dataset
incident_log.head(15)
df['Notes'].unique()

Damage incidents missing description: 500
Possible misclassified incidents: 0

<StringArray>
['Customer reported minor scratch on door',
          'Car returned in good condition',
               'Low fuel warning observed',
         'Tyre pressure alert during trip',
             'AC performance slightly low',
                                       nan,
    'Vehicle returned late due to traffic',
         'Customer requested early pickup',
              'Interior cleaning required',
  'Navigation system malfunction reported',
            'Customer satisfied with ride']
Length: 11, dtype: str

14. Driver license masking and validation (if present).

In [ ]:
#validation
def validate_license(x):
    if pd.isna(x):
        return None
    
    x = str(x)
    
    if re.match(r"DL-\d{10}$", x):
        return x
    else:
        return None

df["Driver_License"] = df["Driver_License"].apply(validate_license)

In [ ]:
#masking
def mask_license(x):
    if pd.isna(x):
        return None
    
    return x[:7] + "XXXXXX"

df["Driver_License"] = df["Driver_License"].apply(mask_license)

15. Promo/coupon code validation & expiry checks.

In [ ]:
# convert pickup timestamp
df["Pickup_TS"] = pd.to_datetime(df["Pickup_TS"], errors="coerce")

# promo expiry dictionary
promo_expiry = {
    "NEW10": "2026-03-31",
    "DISC20": "2026-02-28",
    "SAVE50": "2026-06-30",
    "WELCOME5": "2026-01-31"
}

# convert expiry values to datetime
promo_expiry = {k: pd.to_datetime(v) for k, v in promo_expiry.items()}

# map expiry date to dataset
df["Promo_Expiry"] = df["Promo_Code"].map(promo_expiry)

df["Promo_Status"] = "Valid"

# invalid promo codes
df.loc[df["Promo_Code"].notna() & df["Promo_Expiry"].isna(), "Promo_Status"] = "Invalid_Code"

# expired promo codes
df.loc[(df["Promo_Expiry"].notna()) & (df["Pickup_TS"] > df["Promo_Expiry"]), "Promo_Status"] = "Expired"

In [ ]:
df.head(30)

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_Status,Booking_TS,Pickup_TS,Return_TS,Odo_Start,Odo_End,Fuel_Level,Rate,Promo_Code,City,GPS_Lat,GPS_Lon,Speed,Payment,Driver_License,Damage_Flag,Notes,Vehicle_ID_Invalid,Duration_Hours,Distance_Driven,Refuel_Event,Prev_Return,Overlap_Flag,Promo_Expiry,Promo_Status
2,RES-00003,CUST-1181,CAR-001,Suzuki,Completed,2025-09-03 00:07:00,2025-03-10 00:07:00,2025-03-12 23:07:00,57856.0,58238.0,0.30,2000,DISC20,Delhi,12.914102,77.627323,128 km/h,UPI,DL-9542XXXXXX,Minor,Customer reported minor scratch on door,False,71.000000,382.0,Refueled,NaT,False,2026-02-28,Valid
3654,RES-03655,CUST-0243,CAR-001,Suzuki,Completed,2025-08-04 06:48:00,2025-04-13 06:48:00,2025-04-14 10:48:00,79962.0,80173.0,0.30,2300,WELCOME5,Mumbai,12.886153,77.550280,49kmh,WALLET,DL-9194XXXXXX,Major,Car returned in good condition,False,28.000000,211.0,No Refuel,2025-03-12 23:07:00,False,2026-01-31,Valid
1773,RES-01774,CUST-1755,CAR-001,Suzuki,Cancelled,2025-04-13 00:12:00,2025-04-15 00:12:00,2025-04-15 03:12:00,57390.0,57599.0,0.10,1840,DISC20,Mumbai,12.886021,77.567646,84 km/h,CARD,DL-8187XXXXXX,Minor,Car returned in good condition,False,3.000000,209.0,No Refuel,2025-04-14 10:48:00,False,2026-02-28,Valid
3808,RES-03809,CUST-0799,CAR-001,Suzuki,Cancelled,2025-06-05 00:50:00,2025-06-14 00:50:00,2025-06-15 14:50:00,37275.0,37463.0,0.50,2000,NEW10,Chennai,12.924378,77.625311,76kmh,CARD,DL-3438XXXXXX,Minor,Low fuel warning observed,False,38.000000,188.0,No Refuel,2025-04-15 03:12:00,False,2026-03-31,Valid
1292,RES-01293,CUST-0799,CAR-001,Suzuki,Cancelled,2025-05-01 21:46:00,2025-09-01 21:46:00,2025-12-01 00:46:00,70972.0,70992.0,0.75,1500,DISC20,Mumbai,12.899210,77.624153,NaN,CARD,DL-3438XXXXXX,Minor,Tyre pressure alert during trip,False,2163.000000,20.0,Refueled,2025-06-15 14:50:00,False,2026-02-28,Valid
2592,RES-02593,CUST-1437,CAR-001,Suzuki,Completed,2025-07-06 20:51:00,2025-09-06 20:51:00,2025-10-06 07:51:00,60442.0,60884.0,0.30,2300,DISC20,Delhi,12.948511,77.637527,fast,CARD,DL-9254XXXXXX,NaN,AC performance slightly low,False,707.000000,442.0,No Refuel,2025-12-01 00:46:00,True,2026-02-28,Valid
1460,RES-01461,CUST-0555,CAR-002,Toyota,Completed,2024-12-23 20:04:00,2025-01-01 20:04:00,2025-01-02 20:04:00,39548.0,39636.0,0.10,<NA>,NaN,Delhi,12.914726,77.612034,28kmh,UPI,DL-8144XXXXXX,Minor,AC performance slightly low,False,24.000000,88.0,No Refuel,NaT,False,NaT,Valid
2264,RES-02265,CUST-0117,CAR-002,Toyota,Cancelled,2025-03-05 01:10:00,2025-03-14 01:10:00,2025-11-03 01:10:00,13151.0,13215.0,0.50,2000,NEW10,Mumbai,12.933910,77.563362,138kmh,UPI,DL-5814XXXXXX,Minor,NaN,False,5616.000000,64.0,No Refuel,2025-01-02 20:04:00,False,2026-03-31,Valid
3308,RES-03309,CUST-0243,CAR-002,Toyota,Completed,2025-11-03 21:06:00,2025-03-17 21:06:00,2025-03-19 06:06:00,41606.0,41887.0,0.30,1500,DISC20,Mumbai,12.877574,77.567612,53,NaN,DL-9194XXXXXX,Major,Low fuel warning observed,False,33.000000,281.0,Refueled,2025-11-03 01:10:00,True,2026-02-28,Valid
2193,RES-02194,CUST-1667,CAR-002,Toyota,No_Show,2025-05-25 20:25:00,2025-04-06 15:25:00,2025-06-03 20:25:00,29008.0,29112.0,0.10,1500,NaN,Chennai,12.874858,77.646015,46kmh,CARD,DL-2386XXXXXX,NaN,NaN,False,1397.000000,104.0,No Refuel,2025-03-19 06:06:00,False,NaT,Valid
3082,RES-03083,CUST-1704,CAR-002,Toyota,Completed,2025-01-04 00:07:00,2025-04-13 13:10:00,2025-11-04 00:07:00,33094.0,33526.0,NaN,2300,SAVE50,Delhi,12.922094,77.634890,139 km/h,CARD,DL-6455XXXXXX,NaN,Vehicle returned late due to traffic,False,4906.950000,432.0,No Refuel,2025-06-03 20:25:00,True,2026-06-30,Valid
2225,RES-02226,CUST-0517,CAR-002,Toyota,Cancelled,2025-11-04 15:44:00,2025-04-19 15:44:00,2025-04-22 04:44:00,37104.0,37112.0,0.75,1500,WELCOME5,Delhi,12.902233,77.554764,fast,CARD,DL-6604XXXXXX,NaN,Low fuel warning observed,False,61.000000,8.0,No Refuel,2025-11-04 00:07:00,True,2026-01-31,Valid
3481,RES-03482,CUST-1936,CAR-002,Toyota,Cancelled,2025-09-05 01:06:00,2025-05-15 01:06:00,2025-05-15 14:06:00,25233.0,25620.0,1.00,2000,WELCOME5,Bengaluru,12.858725,77.567423,NaN,CARD,DL-7578XXXXXX,Major,Car returned in good condition,False,13.000000,387.0,Refueled,2025-04-22 04:44:00,False,2026-01-31,Valid
3376,RES-03377,CUST-1190,CAR-002,Toyota,Cancelled,2025-04-30 19:50:00,2025-09-05 19:50:00,2025-12-05 03:00:00,42283.0,42493.0,0.50,2300,NaN,Bengaluru,12.865467,77.632876,106kmh,CARD,DL-6729XXXXXX,NaN,Customer reported minor scratch on door,False,2167.166667,210.0,Refueled,2025-05-15 14:06:00,False,NaT,Valid
3584,RES-03585,CUST-0757,CAR-003,Hatchback,Completed,2025-05-30 14:18:00,2025-01-06 13:09:00,2025-02-06 13:09:00,76958.0,77012.0,0.75,2500,WELCOME5,Chennai,12.927337,77.648629,128 km/h,CARD,DL-3869XXXXXX,Major,Customer requested early pickup,False,744.000000,54.0,No Refuel,NaT,False,2026-01-31,Valid
3636,RES-03637,CUST-0983,CAR-003,Hatchback,Completed,2025-01-08 13:19:00,2025-01-14 13:19:00,2025-01-17 06:19:00,45785.0,45816.0,0.75,2000,SAVE50,Bengaluru,12.860834,77.591870,NaN,CARD,DL-7906XXXXXX,NaN,Vehicle returned late due to traffic,False,65.000000,31.0,Refueled,2025-02-06 13:09:00,True,2026-06-30,Valid
2230,RES-02231,CUST-1260,CAR-003,Hatchback,No_Show,2025-02-03 18:56:00,2025-02-12 18:56:00,2025-02-14 22:56:00,47384.0,47445.0,NaN,1840,DISC20,NaN,12.887082,77.627755,29 km/h,CARD,DL-8784XXXXXX,Major,AC performance slightly low,False,52.000000,61.0,No Refuel,2025-01-17 06:19:00,False,2026-02-28,Valid
3944,RES-03945,CUST-0018,CAR-003,Hatchback,Cancelled,2025-02-17 16:14:00,2025-02-18 16:14:00,2025-02-18 21:14:00,13203.0,13431.0,NaN,2000,SAVE50,Bengaluru,12.911415,77.571113,99kmh,CASH,DL-1575XXXXXX,NaN,Car returned in good condition,False,5.000000,228.0,No Refuel,2025-02-14 22:56:00,False,2026-06-30,Valid
1851,RES-01852,CUST-0376,CAR-003,Hatchback,Cancelled,2025-03-31 09:44:00,2025-03-04 09:44:00,2025-03-04 19:02:00,72332.0,72627.0,1.00,2000,SAVE50,Bengaluru,12.913364,77.562468,65kmh,CARD,DL-7114XXXXXX,NaN,Interior cleaning required,False,9.300000,295.0,Refueled,2025-02-18 21:14:00,False,2026-06-30,Valid
3107,RES-03108,CUST-1044,CAR-003,Hatchback,Cancelled,2025-04-19 19:12:00,2025-04-25 14:12:00,2025-04-25 19:12:00,32711.0,33209.0,0.10,1500,NEW10,Bengaluru,12.851358,77.552328,84,NaN,DL-9787XXXXXX,NaN,Vehicle returned late due to traffic,False,5.000000,498.0,No Refuel,2025-03-04 19:02:00,False,2026-03-31,Valid
676,RES-00677,CUST-0898,CAR-003,Hatchback,Cancelled,2025-01-02 07:15:00,2025-05-02 06:40:00,2025-07-02 22:40:00,62121.0,62620.0,0.75,1800,DISC20,Mumbai,12.923296,77.595402,fast,CARD,DL-3256XXXXXX,Minor,Interior cleaning required,False,1480.000000,499.0,No Refuel,2025-04-25 19:12:00,False,2026-02-28,Valid
788,RES-00789,CUST-0595,CAR-003,Hatchback,No_Show,2025-07-06 15:54:00,2025-06-17 15:54:00,2025-06-19 05:54:00,15242.0,15564.0,0.75,2500,WELCOME5,Bengaluru,12.851098,77.625257,135 km/h,NaN,DL-4293XXXXXX,Minor,Customer reported minor scratch on door,False,38.000000,322.0,No Refuel,2025-07-02 22:40:00,True,2026-01-31,Valid
1726,RES-01727,CUST-0544,CAR-003,Hatchback,No_Show,2024-12-30 03:16:00,2025-08-01 03:01:00,2025-09-01 22:58:00,29649.0,30135.0,0.25,1800,NEW10,Chennai,12.877659,77.600966,21 km/h,NaN,DL-5405XXXXXX,NaN,AC performance slightly low,False,763.950000,486.0,No Refuel,2025-06-19 05:54:00,False,2026-03-31,Valid
879,RES-00880,CUST-1173,CAR-005,SUV,No_Show,2025-08-01 12:12:00,2025-01-14 11:00:00,2025-01-16 09:19:00,48251.0,48347.0,0.75,1800,NaN,NaN,12.915540,77.574737,29,CARD,DL-5903XXXXXX,Major,NaN,False,46.316667,96.0,No Refuel,NaT,False,NaT,Valid
4409,RES-04410,CUST-0570,CAR-005,SUV,Completed,2025-02-13 00:31:00,2025-02-14 01:19:00,2025-02-14 10:18:00,61456.0,61863.0,0.50,1800,WELCOME5,Chennai,12.855598,77.633814,45,CASH,DL-1381XXXXXX,Major,AC performance slightly low,False,8.983333,407.0,No Refuel,2025-01-16 09:19:00,False,2026-01-31,Valid
2001,RES-02002,CUST-0705,CAR-005,SUV,Completed,2025-12-02 06:58:00,2025-02-22 06:58:00,2025-02-24 01:58:00,13088.0,13518.0,1.00,2300,NEW10,Mumbai,12.942336,77.604381,61kmh,WALLET,DL-9852XXXXXX,Major,Low fuel warning observed,False,43.000000,430.0,No Refuel,2025-02-14 10:18:00,False,2026-03-31,Valid
2262,RES-02263,CUST-0271,CAR-005,SUV,Cancelled,2025-02-25 21:47:00,2025-03-03 21:47:00,2025-06-03 21:02:00,29372.0,29453.0,0.50,2000,NaN,Mumbai,12.864591,77.621166,fast,NaN,DL-6830XXXXXX,Major,Vehicle returned late due to traffic,False,2207.250000,81.0,Refueled,2025-02-24 01:58:00,False,NaT,Valid
4456,RES-04457,CUST-0520,CAR-005,SUV,No_Show,2025-03-22 21:30:00,2025-03-23 21:30:00,2025-03-25 01:30:00,31387.0,31393.0,0.25,1500,NaN,NaN,12.927048,77.577277,NaN,UPI,DL-4605XXXXXX,Minor,NaN,False,28.000000,6.0,No Refuel,2025-06-03 21:02:00,True,NaT,Valid
1986,RES-01987,CUST-1784,CAR-005,SUV,No_Show,2025-01-31 10:20:00,2025-04-02 11:14:00,2025-06-02 15:20:00,13389.0,13404.0,0.50,1500,NEW10,Chennai,12.900426,77.581547,NaN,NaN,DL-5196XXXXXX,Major,NaN,False,1468.100000,15.0,No Refuel,2025-03-25 01:30:00,False,2026-03-31,Valid
3347,RES-03348,CUST-1032,CAR-005,SUV,Cancelled,2025-05-05 04:14:00,2025-05-09 04:14:00,2025-11-05 19:14:00,41730.0,41813.0,1.00,2000,NaN,Delhi,12.851110,77.608952,87 km/h,CARD,DL-5728XXXXXX,Major,Low fuel warning observed,False,4335.000000,83.0,Refueled,2025-06-02 15:20:00,True,NaT,Valid

16. Telematics GPS join and jitter smoothing.

In [ ]:
# 1 check duplicates
df[['GPS_Lat', 'GPS_Lon']].duplicated().sum()

# 2 clean quote artifacts, convert to numeric, and handle missing values
df['GPS_Lat'] = pd.to_numeric(
    df['GPS_Lat'].astype(str).str.strip().str.replace(r"^'+|'+$", "", regex=True),
    errors='coerce'
 )
df['GPS_Lon'] = pd.to_numeric(
    df['GPS_Lon'].astype(str).str.strip().str.replace(r"^'+|'+$", "", regex=True),
    errors='coerce'
 )
df['GPS_Lat'] = df['GPS_Lat'].interpolate()
df['GPS_Lon'] = df['GPS_Lon'].interpolate()

# 3 smooth jitter and round to 4 decimals
df['GPS_Lat'] = df['GPS_Lat'].rolling(window=3, min_periods=1).mean().round(4)
df['GPS_Lon'] = df['GPS_Lon'].rolling(window=3, min_periods=1).mean().round(4)

df[['GPS_Lat', 'GPS_Lon']].dtypes

GPS_Lat    float64
GPS_Lon    float64
dtype: object

17. Speeding/harsh events normalization from telematics.

In [ ]:
# Inspect Speed Column
df["Speed"].head()

# Convert Speed Column to String
df["Speed"] = df["Speed"].astype(str)

# Remove Units (kmh and km/h)
df["Speed"] = df["Speed"].str.replace("km/h","", regex=False)
df["Speed"] = df["Speed"].str.replace("kmh","", regex=False)

# Convert "fast" to Numeric Speed

# Since "fast" means driving faster than normal, we convert it to 90 km/h.

df["Speed"] = df["Speed"].replace("fast", 90)

# Convert Entire Column to Numeric
df["Speed"] = pd.to_numeric(df["Speed"], errors="coerce")


# Create Driver Behavior Classification

def classify_speed(speed):

    if pd.isna(speed):
        return "Unknown"

    elif speed <= 80:
        return "Normal Driving"

    elif speed <= 100:
        return "Fast Driving"

    else:
        return "Speeding"


df["Driver_Behavior"] = df["Speed"].apply(classify_speed)


# Verify Result

df[["Speed","Driver_Behavior"]].head(10)

      Speed Driver_Behavior
2     128.0        Speeding
3654   49.0  Normal Driving
1773   84.0    Fast Driving
3808   76.0  Normal Driving
1292    NaN         Unknown
2592   90.0    Fast Driving
1460   28.0  Normal Driving
2264  138.0        Speeding
3308   53.0  Normal Driving
2193   46.0  Normal Driving

18. PII redaction in notes and feedback.

In [ ]:
df['Notes'] = df['Notes'].str.replace(r'\b\d{10}\b', '[REDACTED]', regex=True)
df['Notes'] = df['Notes'].str.replace(r'\S+@\S+', '[REDACTED]', regex=True)
df['Notes'] = df['Notes'].str.replace(r'\b[A-Z0-9]{8,}\b', '[REDACTED]', regex=True)

19. Rate plan mapping to master tariffs.

In [ ]:
df['Rate'] = df['Rate'].astype(str)
df['Rate'] = df['Rate'].str.replace('[^0-9.]', '', regex=True)
df['Rate'] = pd.to_numeric(df['Rate'], errors='coerce')

20. Tax/GST computation validation.

In [ ]:
# USE CASE 20: Tax/GST computation validation (hour-based billing)

df["Rate"] = pd.to_numeric(df["Rate"], errors="coerce")
df["Duration_Hours"] = pd.to_numeric(df["Duration_Hours"], errors="coerce")

billable_hours = df["Duration_Hours"].clip(lower=0).fillna(0)
df["Total_Amount"] = ((df["Rate"] / 24) * billable_hours * 1.18).round(2)

# Only completed trips are billable in this synthetic pipeline
df.loc[~df["Booking_Status"].eq("Completed"), "Total_Amount"] = 0.0

In [ ]:
df['Vehicle_ID'].unique()

<StringArray>
['CAR-001', 'CAR-002', 'CAR-003', 'CAR-005', 'CAR-006', 'CAR-007', 'CAR-008',
 'CAR-009', 'CAR-010', 'CAR-011',
 ...
 'CAR-592', 'CAR-593', 'CAR-594', 'CAR-595', 'CAR-596', 'CAR-597', 'CAR-598',
 'CAR-599', 'CAR-600',       nan]
Length: 601, dtype: str

In [ ]:
df["Pickup_TS"] = pd.to_datetime(df["Pickup_TS"])
df["Return_TS"] = pd.to_datetime(df["Return_TS"])

df["Pickup_TS"] = df["Pickup_TS"].fillna(df["Pickup_TS"].mean())
df["Return_TS"] = df["Return_TS"].fillna(df["Return_TS"].mean())
df["Pickup_TS"] = df["Pickup_TS"].fillna(df["Pickup_TS"].mean())
df["Return_TS"] = df["Return_TS"].fillna(df["Return_TS"].mean())

df["Fuel_Level"] = df["Fuel_Level"].fillna(df["Fuel_Level"].mean())
df["Rate"] = df["Rate"].fillna(df["Rate"].mean())


df["Promo_Code"] = df["Promo_Code"].fillna(df["Promo_Code"].mode()[0])
df["City"] = df["City"].fillna(df["City"].mode()[0])


df["Speed"] = df["Speed"].fillna(df["Speed"].median())
df["Payment"] = df["Payment"].fillna(df["Payment"].mode()[0])

df["Damage_Flag"] = df["Damage_Flag"].fillna("None")

df["Notes"] = df["Notes"].fillna("No Notes")

df["Duration_Hours"] = df["Duration_Hours"].round(2)

In [ ]:
df["Booking_TS"] = pd.to_datetime(df["Booking_TS"])
df["Pickup_TS"] = pd.to_datetime(df["Pickup_TS"])

df.loc[df["Booking_TS"] > df["Pickup_TS"], "Booking_TS"] = df["Pickup_TS"] - pd.Timedelta(days=1)
df.head(20)

,Reservation_ID,Customer_ID,Vehicle_ID,Vehicle_Class,Booking_Status,Booking_TS,Pickup_TS,Return_TS,Odo_Start,Odo_End,Fuel_Level,Rate,Promo_Code,City,GPS_Lat,GPS_Lon,Speed,Payment,Driver_License,Damage_Flag,Notes,Vehicle_ID_Invalid,Duration_Hours,Distance_Driven,Refuel_Event,Prev_Return,Overlap_Flag,Promo_Expiry,Promo_Status,Driver_Behavior,Total_Amount
2,RES-00003,CUST-1181,CAR-001,Suzuki,Completed,2025-03-09 00:07:00,2025-03-10 00:07:00,2025-03-12 23:07:00,57856.0,58238.0,0.300000,2000.000000,DISC20,Delhi,12.9141,77.6273,128.0,UPI,DL-9542XXXXXX,Minor,Customer reported minor scratch on door,False,71.00,382.0,Refueled,NaT,False,2026-02-28,Valid,Speeding,2360.0
3654,RES-03655,CUST-0243,CAR-001,Suzuki,Completed,2025-04-12 06:48:00,2025-04-13 06:48:00,2025-04-14 10:48:00,79962.0,80173.0,0.300000,2300.000000,WELCOME5,Mumbai,12.9001,77.5888,49.0,WALLET,DL-9194XXXXXX,Major,Car returned in good condition,False,28.00,211.0,No Refuel,2025-03-12 23:07:00,False,2026-01-31,Valid,Normal Driving,2714.0
1773,RES-01774,CUST-1755,CAR-001,Suzuki,Cancelled,2025-04-13 00:12:00,2025-04-15 00:12:00,2025-04-15 03:12:00,57390.0,57599.0,0.100000,1840.000000,DISC20,Mumbai,12.8954,77.5817,84.0,CARD,DL-8187XXXXXX,Minor,Car returned in good condition,False,3.00,209.0,No Refuel,2025-04-14 10:48:00,False,2026-02-28,Valid,Fast Driving,2171.2
3808,RES-03809,CUST-0799,CAR-001,Suzuki,Cancelled,2025-06-05 00:50:00,2025-06-14 00:50:00,2025-06-15 14:50:00,37275.0,37463.0,0.500000,2000.000000,NEW10,Chennai,12.8989,77.5811,76.0,CARD,DL-3438XXXXXX,Minor,Low fuel warning observed,False,38.00,188.0,No Refuel,2025-04-15 03:12:00,False,2026-03-31,Valid,Normal Driving,2360.0
1292,RES-01293,CUST-0799,CAR-001,Suzuki,Cancelled,2025-05-01 21:46:00,2025-09-01 21:46:00,2025-12-01 00:46:00,70972.0,70992.0,0.750000,1500.000000,DISC20,Mumbai,12.9032,77.6057,90.0,CARD,DL-3438XXXXXX,Minor,Tyre pressure alert during trip,False,2163.00,20.0,Refueled,2025-06-15 14:50:00,False,2026-02-28,Valid,Unknown,1770.0
2592,RES-02593,CUST-1437,CAR-001,Suzuki,Completed,2025-07-06 20:51:00,2025-09-06 20:51:00,2025-10-06 07:51:00,60442.0,60884.0,0.300000,2300.000000,DISC20,Delhi,12.9240,77.6290,90.0,CARD,DL-9254XXXXXX,None,AC performance slightly low,False,707.00,442.0,No Refuel,2025-12-01 00:46:00,True,2026-02-28,Valid,Fast Driving,2714.0
1460,RES-01461,CUST-0555,CAR-002,Toyota,Completed,2024-12-23 20:04:00,2025-01-01 20:04:00,2025-01-02 20:04:00,39548.0,39636.0,0.100000,1835.274591,NEW10,Delhi,12.9208,77.6246,28.0,UPI,DL-8144XXXXXX,Minor,AC performance slightly low,False,24.00,88.0,No Refuel,NaT,False,NaT,Valid,Normal Driving,NaN
2264,RES-02265,CUST-0117,CAR-002,Toyota,Cancelled,2025-03-05 01:10:00,2025-03-14 01:10:00,2025-11-03 01:10:00,13151.0,13215.0,0.500000,2000.000000,NEW10,Mumbai,12.9324,77.6043,138.0,UPI,DL-5814XXXXXX,Minor,No Notes,False,5616.00,64.0,No Refuel,2025-01-02 20:04:00,False,2026-03-31,Valid,Speeding,2360.0
3308,RES-03309,CUST-0243,CAR-002,Toyota,Completed,2025-03-16 21:06:00,2025-03-17 21:06:00,2025-03-19 06:06:00,41606.0,41887.0,0.300000,1500.000000,DISC20,Mumbai,12.9087,77.5810,53.0,CARD,DL-9194XXXXXX,Major,Low fuel warning observed,False,33.00,281.0,Refueled,2025-11-03 01:10:00,True,2026-02-28,Valid,Normal Driving,1770.0
2193,RES-02194,CUST-1667,CAR-002,Toyota,No_Show,2025-04-05 15:25:00,2025-04-06 15:25:00,2025-06-03 20:25:00,29008.0,29112.0,0.100000,1500.000000,NEW10,Chennai,12.8954,77.5923,46.0,CARD,DL-2386XXXXXX,None,No Notes,False,1397.00,104.0,No Refuel,2025-03-19 06:06:00,False,NaT,Valid,Normal Driving,1770.0
3082,RES-03083,CUST-1704,CAR-002,Toyota,Completed,2025-01-04 00:07:00,2025-04-13 13:10:00,2025-11-04 00:07:00,33094.0,33526.0,0.510431,2300.000000,SAVE50,Delhi,12.8915,77.6162,139.0,CARD,DL-6455XXXXXX,None,Vehicle returned late due to traffic,False,4906.95,432.0,No Refuel,2025-06-03 20:25:00,True,2026-06-30,Valid,Speeding,2714.0
2225,RES-02226,CUST-0517,CAR-002,Toyota,Cancelled,2025-04-18 15:44:00,2025-04-19 15:44:00,2025-04-22 04:44:00,37104.0,37112.0,0.750000,1500.000000,WELCOME5,Delhi,12.8997,77.6119,90.0,CARD,DL-6604XXXXXX,None,Low fuel warning observed,False,61.00,8.0,No Refuel,2025-11-04 00:07:00,True,2026-01-31,Valid,Fast Driving,1770.0
3481,RES-03482,CUST-1936,CAR-002,Toyota,Cancelled,2025-05-14 01:06:00,2025-05-15 01:06:00,2025-05-15 14:06:00,25233.0,25620.0,1.000000,2000.000000,WELCOME5,Bengaluru,12.8944,77.5857,90.0,CARD,DL-7578XXXXXX,Major,Car returned in good condition,False,13.00,387.0,Refueled,2025-04-22 04:44:00,False,2026-01-31,Valid,Unknown,2360.0
3376,RES-03377,CUST-1190,CAR-002,Toyota,Cancelled,2025-04-30 19:50:00,2025-09-05 19:50:00,2025-12-05 03:00:00,42283.0,42493.0,0.500000,2300.000000,NEW10,Bengaluru,12.8755,77.5850,106.0,CARD,DL-6729XXXXXX,None,Customer reported minor scratch on door,False,2167.17,210.0,Refueled,2025-05-15 14:06:00,False,NaT,Valid,Speeding,2714.0
3584,RES-03585,CUST-0757,CAR-003,Hatchback,Completed,2025-01-05 13:09:00,2025-01-06 13:09:00,2025-02-06 13:09:00,76958.0,77012.0,0.750000,2500.000000,WELCOME5,Chennai,12.8838,77.6163,128.0,CARD,DL-3869XXXXXX,Major,Customer requested early pickup,False,744.00,54.0,No Refuel,NaT,False,2026-01-31,Valid,Speeding,2950.0
3636,RES-03637,CUST-0983,CAR-003,Hatchback,Completed,2025-01-08 13:19:00,2025-01-14 13:19:00,2025-01-17 06:19:00,45785.0,45816.0,0.750000,2000.000000,SAVE50,Bengaluru,12.8845,77.6245,90.0,CARD,DL-7906XXXXXX,None,Vehicle returned late due to traffic,False,65.00,31.0,Refueled,2025-02-06 13:09:00,True,2026-06-30,Valid,Unknown,2360.0
2230,RES-02231,CUST-1260,CAR-003,Hatchback,No_Show,2025-02-03 18:56:00,2025-02-12 18:56:00,2025-02-14 22:56:00,47384.0,47445.0,0.510431,1840.000000,DISC20,Delhi,12.8918,77.6228,29.0,CARD,DL-8784XXXXXX,Major,AC performance slightly low,False,52.00,61.0,No Refuel,2025-01-17 06:19:00,False,2026-02-28,Valid,Normal Driving,2171.2
3944,RES-03945,CUST-0018,CAR-003,Hatchback,Cancelled,2025-02-17 16:14:00,2025-02-18 16:14:00,2025-02-18 21:14:00,13203.0,13431.0,0.510431,2000.000000,SAVE50,Bengaluru,12.8864,77.5969,99.0,CASH,DL-1575XXXXXX,None,Car returned in good condition,False,5.00,228.0,No Refuel,2025-02-14 22:56:00,False,2026-06-30,Valid,Fast Driving,2360.0
1851,RES-01852,CUST-0376,CAR-003,Hatchback,Cancelled,2025-03-03 09:44:00,2025-03-04 09:44:00,2025-03-04 19:02:00,72332.0,72627.0,1.000000,2000.000000,SAVE50,Bengaluru,12.9040,77.5871,65.0,CARD,DL-7114XXXXXX,None,Interior cleaning required,False,9.30,295.0,Refueled,2025-02-18 21:14:00,False,2026-06-30,Valid,Normal Driving,2360.0
3107,RES-03108,CUST-1044,CAR-003,Hatchback,Cancelled,2025-04-19 19:12:00,2025-04-25 14:12:00,2025-04-25 19:12:00,32711.0,33209.0,0.100000,1500.000000,NEW10,Bengaluru,12.8920,77.5620,84.0,CARD,DL-9787XXXXXX,None,Vehicle returned late due to traffic,False,5.00,498.0,No Refuel,2025-03-04 19:02:00,False,2026-03-31,Valid,Fast Driving,1770.0

In [ ]:
df.loc[df["Booking_Status"] == "Cancelled", "Odo_End"] = df["Odo_Start"]
df.loc[df["Booking_Status"] == "Cancelled", "Total_Amount"] = 0

df["Total_Amount"] = df["Total_Amount"].fillna(df["Total_Amount"].mean())

In [ ]:
df["Fuel_Level"] = df["Fuel_Level"].round(2)
df["Rate"] = df["Rate"].round(2)
df["Total_Amount"] = df["Total_Amount"].round(2)

In [ ]:
df["Distance_Driven"] = df["Odo_End"] - df["Odo_Start"]
df["Vehicle_ID"] = df["Vehicle_ID"].fillna("CAR-600")
df.loc[df["Promo_Expiry"].isnull(), "Promo_Status"] = "Invalid"

In [ ]:
import numpy as np
from geopy.geocoders import Nominatim
import time

# Initialize geocoder
geolocator = Nominatim(user_agent="city_lat_long_generator")

# Get unique cities
cities = df["City"].dropna().unique()

city_coords = {}

# Get base coordinates for each city
for city in cities:
    try:
        location = geolocator.geocode(city)
        if location:
            city_coords[city] = (location.latitude, location.longitude)
        else:
            city_coords[city] = (np.nan, np.nan)
        time.sleep(1)
    except:
        city_coords[city] = (np.nan, np.nan)

# Function to generate random nearby coordinates
def generate_random_coords(city):
    lat, lon = city_coords.get(city, (np.nan, np.nan))

    if pd.isna(lat) or pd.isna(lon):
        return pd.Series([np.nan, np.nan])

    lat_random = lat + np.random.uniform(-0.02, 0.02)
    lon_random = lon + np.random.uniform(-0.02, 0.02)

    # round to 4 decimal places
    lat_random = round(lat_random, 4)
    lon_random = round(lon_random, 4)

    return pd.Series([lat_random, lon_random])

# Apply to dataframe
df[["GPS_Lat", "GPS_Lon"]] = df["City"].apply(generate_random_coords)

In [ ]:
# Save cleaned dataset to CSV
df.to_csv("../Datasets/car_rental_cleaned_dataset.csv", index=False)
print("Cleaned dataset saved to 'car_rental_cleaned_dataset.csv'")
print(f"Final dataset shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")

Cleaned dataset saved to 'car_rental_cleaned_dataset.csv'
Final dataset shape: (4527, 31)
Columns: ['Reservation_ID', 'Customer_ID', 'Vehicle_ID', 'Vehicle_Class', 'Booking_Status', 'Booking_TS', 'Pickup_TS', 'Return_TS', 'Odo_Start', 'Odo_End', 'Fuel_Level', 'Rate', 'Promo_Code', 'City', 'GPS_Lat', 'GPS_Lon', 'Speed', 'Payment', 'Driver_License', 'Damage_Flag', 'Notes', 'Vehicle_ID_Invalid', 'Duration_Hours', 'Distance_Driven', 'Refuel_Event', 'Prev_Return', 'Overlap_Flag', 'Promo_Expiry', 'Promo_Status', 'Driver_Behavior', 'Total_Amount']